In [20]:
import pandas as pd

# Data Electricity

---

Kesimpulan: dataset yang dipakai tipe **Balanced**

## Balanced

In [21]:
df_balanced = pd.read_csv("Contoh dataset\EIA930_BALANCE_2026_Jan_Jun.csv")
df_balanced.head()

,Balancing Authority,Data Date,Hour Number,Local Time at End of Hour,UTC Time at End of Hour,Demand Forecast (MW),Demand (MW),Net Generation (MW),Total Interchange (MW),Sum(Valid DIBAs) (MW),...,Net Generation (MW) from Solar witho Integrated Battery Storage (Adjusted),Net Generation (MW) from Wind without Integrated Battery Storage (Adjusted),Net Generation (MW) from Wind with Integrated Battery Storage (Adjusted),Net Generation (MW) from Battery Storage (Adjusted),Net Generation (MW) from Other Energy Storage (Adjusted),Net Generation (MW) from Unknown Energy Storage (Adjusted),Net Generation (MW) from Geothermal (Adjusted),Net Generation (MW) from Other Fuel Sources (Adjusted),Net Generation (MW) from Unknown Fuel Sources (Adjusted),Region
0,AECI,01/01/2026,1,01/01/2026 1:00:00 AM,01/01/2026 7:00:00 AM,2706.0,2625.0,2942.0,317.0,317.0,...,NaN,602.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MIDW
1,AECI,01/01/2026,2,01/01/2026 2:00:00 AM,01/01/2026 8:00:00 AM,2638.0,2618.0,2895.0,277.0,277.0,...,NaN,410.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MIDW
2,AECI,01/01/2026,3,01/01/2026 3:00:00 AM,01/01/2026 9:00:00 AM,2627.0,2600.0,3036.0,436.0,436.0,...,NaN,262.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MIDW
3,AECI,01/01/2026,4,01/01/2026 4:00:00 AM,01/01/2026 10:00:00 AM,2649.0,2673.0,2971.0,298.0,298.0,...,NaN,105.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MIDW
4,AECI,01/01/2026,5,01/01/2026 5:00:00 AM,01/01/2026 11:00:00 AM,2726.0,2722.0,3107.0,385.0,385.0,...,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MIDW

In [22]:
df_balanced.columns

Index(['Balancing Authority', 'Data Date', 'Hour Number',
       'Local Time at End of Hour', 'UTC Time at End of Hour',
       'Demand Forecast (MW)', 'Demand (MW)', 'Net Generation (MW)',
       'Total Interchange (MW)', 'Sum(Valid DIBAs) (MW)',
       'Demand (MW) (Imputed)', 'Net Generation (MW) (Imputed)',
       'Total Interchange (MW) (Imputed)', 'Demand (MW) (Adjusted)',
       'Net Generation (MW) (Adjusted)', 'Total Interchange (MW) (Adjusted)',
       'Net Generation (MW) from Coal', 'Net Generation (MW) from Natural Gas',
       'Net Generation (MW) from Nuclear',
       'Net Generation (MW) from All Petroleum Products',
       'Net Generation (MW) from Hydropower Excluding Pumped Storage',
       'Net Generation (MW) from Pumped Storage',
       'Net Generation (MW) from Solar without Integrated Battery Storage',
       'Net Generation (MW) from Solar with Integrated Battery Storage',
       'Net Generation (MW) from Wind without Integrated Battery Storage',
       'Net Generation (MW) from Wind with Integrated Battery Storage',
       'Net Generation (MW) from Battery Storage',
       'Net Generation (MW) from Other Energy Storage',
       'Net Generation (MW) from Unknown Energy Storage',
       'Net Generation (MW) from Geothermal',
       'Net Generation (MW) from Other Fuel Sources',
       'Net Generation (MW) from Unknown Fuel Sources',
       'Net Generation (MW) from Coal (Imputed)',
       'Net Generation (MW) from Natural Gas (Imputed)',
       'Net Generation (MW) from Nuclear (Imputed)',
       'Net Generation (MW) from All Petroleum Products (Imputed)',
       'Net Generation (MW) from Hydropower Excluding Pumped Storage (Imputed)',
       'Net Generation (MW) from Pumped Storage (Imputed)',
       'Net Generation (MW) from Solar without Integrated Battery Storage (Imputed)',
       'Net Generation (MW) from Solar with Integrated Battery Storage (Imputed)',
       'Net Generation (MW) from Wind without Integrated Battery Storage (Imputed)',
       'Net Generation (MW) from Wind with Integrated Battery Storage (Imputed)',
       'Net Generation (MW) from Battery Storage (Imputed)',
       'Net Generation (MW) from Other Energy Storage (Imputed)',
       'Net Generation (MW) from Unknown Energy Storage (Imputed)',
       'Net Generation (MW) from Geothermal (Imputed)',
       'Net Generation (MW) from Other Fuel Sources (Imputed)',
       'Net Generation (MW) from Unknown Fuel Sources (Imputed)',
       'Net Generation (MW) from Coal (Adjusted)',
       'Net Generation (MW) from Natural Gas (Adjusted)',
       'Net Generation (MW) from Nuclear (Adjusted)',
       'Net Generation (MW) from All Petroleum Products (Adjusted)',
       'Net Generation (MW) from Hydropower Excluding Pumped Storage (Adjusted)',
       'Net Generation (MW) from Pumped Storage  (Adjusted)',
       'Net Generation (MW) from Solar without Integrated Battery Storage (Adjusted)',
       'Net Generation (MW) from Solar witho Integrated Battery Storage (Adjusted)',
       'Net Generation (MW) from Wind without Integrated Battery Storage (Adjusted)',
       'Net Generation (MW) from Wind with Integrated Battery Storage (Adjusted)',
       'Net Generation (MW) from Battery Storage (Adjusted)',
       'Net Generation (MW) from Other Energy Storage (Adjusted)',
       'Net Generation (MW) from Unknown Energy Storage (Adjusted)',
       'Net Generation (MW) from Geothermal (Adjusted)',
       'Net Generation (MW) from Other Fuel Sources (Adjusted)',
       'Net Generation (MW) from Unknown Fuel Sources (Adjusted)', 'Region'],
      dtype='object')

In [23]:
# for numerical data
df_balanced.describe().to_csv('EksplorasiSingkat/balanced_numerical_description.csv')
df_balanced.describe()

,Hour Number,Demand Forecast (MW),Demand (MW),Net Generation (MW),Total Interchange (MW),Sum(Valid DIBAs) (MW),Demand (MW) (Imputed),Net Generation (MW) (Imputed),Total Interchange (MW) (Imputed),Demand (MW) (Adjusted),...,Net Generation (MW) from Solar without Integrated Battery Storage (Adjusted),Net Generation (MW) from Solar witho Integrated Battery Storage (Adjusted),Net Generation (MW) from Wind without Integrated Battery Storage (Adjusted),Net Generation (MW) from Wind with Integrated Battery Storage (Adjusted),Net Generation (MW) from Battery Storage (Adjusted),Net Generation (MW) from Other Energy Storage (Adjusted),Net Generation (MW) from Unknown Energy Storage (Adjusted),Net Generation (MW) from Geothermal (Adjusted),Net Generation (MW) from Other Fuel Sources (Adjusted),Net Generation (MW) from Unknown Fuel Sources (Adjusted)
count,181222.000000,157638.000000,1.567180e+05,1.776310e+05,177503.000000,174270.000000,479.000000,768.000000,220.0,157153.000000,...,127742.000000,35777.000000,91969.000000,2999.0,53005.000000,5998.000000,2986.000000,14996.000000,92752.000000,2999.0
mean,12.496827,8914.425500,9.053018e+03,7.925736e+03,-60.503090,-68.242704,11607.703549,7499.397135,0.0,9038.516446,...,735.823488,51.145708,2037.987615,0.0,17.316517,0.009670,-376.570998,230.948186,213.190993,0.0
std,6.920524,18524.631101,1.964454e+04,1.890135e+04,1422.482782,1655.464049,22164.840194,18239.082699,0.0,18365.830676,...,2663.877242,111.583635,4729.350010,0.0,576.908747,1.009166,557.877889,285.850882,921.532685,0.0
min,1.000000,-25409.000000,-4.409900e+04,-2.498900e+04,-21604.000000,-327301.000000,18.000000,-9.000000,0.0,0.000000,...,-190.000000,-300.000000,-16.000000,0.0,-6685.000000,-1.000000,-2135.000000,-1.000000,-9504.000000,0.0
25%,6.000000,746.000000,7.730000e+02,5.730000e+02,-475.000000,-492.000000,832.500000,110.750000,0.0,773.000000,...,0.000000,0.000000,31.000000,0.0,-7.000000,0.000000,-769.500000,9.000000,18.000000,0.0
50%,12.000000,2144.000000,2.389000e+03,1.605000e+03,-8.000000,-20.000000,2699.000000,1517.000000,0.0,2391.000000,...,1.000000,2.000000,265.000000,0.0,0.000000,0.000000,-10.000000,32.000000,56.000000,0.0
75%,18.000000,5909.000000,6.304000e+03,5.614000e+03,434.000000,410.000000,4729.500000,3813.000000,0.0,6300.000000,...,279.000000,66.000000,1111.000000,0.0,37.000000,0.000000,-5.000000,435.000000,202.000000,0.0
max,24.000000,271191.000000,2.576875e+06,2.576906e+06,45575.000000,45575.000000,90172.000000,93361.000000,0.0,139410.000000,...,33645.000000,602.000000,28408.000000,0.0,9294.000000,25.000000,0.000000,816.000000,12993.000000,0.0

In [24]:
# for numerical data
df_balanced.describe(include="object").to_csv('EksplorasiSingkat/balanced_categorical_description.csv')
df_balanced.describe(include="object")

,Balancing Authority,Data Date,Local Time at End of Hour,UTC Time at End of Hour,Region
count,181222,181222,181222,181222,181222
unique,62,126,3024,3026,13
top,LGEE,01/01/2026,01/01/2026 1:00:00 AM,04/01/2026 6:00:00 AM,NW
freq,3024,1440,60,61,60389

In [25]:
balanced_info = pd.DataFrame({
    "column": df_balanced.columns,
    "non_null_count": df_balanced.notna().sum().values,
    "null_count": df_balanced.isna().sum().values,
    "dtype": df_balanced.dtypes.astype(str).values
})

balanced_info.to_csv("EksplorasiSingkat/balanced_info.csv", index=False)
df_balanced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181222 entries, 0 to 181221
Data columns (total 65 columns):
 #   Column                                                                        Non-Null Count   Dtype
---  ------                                                                        --------------   -----
 0   Balancing Authority                                                           181222 non-null  object
 1   Data Date                                                                     181222 non-null  object
 2   Hour Number                                                                   181222 non-null  int64
 3   Local Time at End of Hour                                                     181222 non-null  object
 4   UTC Time at End of Hour                                                       181222 non-null  object
 5   Demand Forecast (MW)                                                          157638 non-null  float64
 6   Demand (MW)                                                                   156718 non-null  float64
 7   Net Generation (MW)                                                           177631 non-null  float64
 8   Total Interchange (MW)                                                        177503 non-null  float64
 9   Sum(Valid DIBAs) (MW)                                                         174270 non-null  float64
 10  Demand (MW) (Imputed)                                                         479 non-null     float64
 11  Net Generation (MW) (Imputed)                                                 768 non-null     float64
 12  Total Interchange (MW) (Imputed)                                              220 non-null     float64
 13  Demand (MW) (Adjusted)                                                        157153 non-null  float64
 14  Net Generation (MW) (Adjusted)                                                178124 non-null  float64
 15  Total Interchange (MW) (Adjusted)                                             177503 non-null  float64
 16  Net Generation (MW) from Coal                                                 99661 non-null   float64
 17  Net Generation (MW) from Natural Gas                                          145249 non-null  float64
 18  Net Generation (MW) from Nuclear                                              53566 non-null   float64
 19  Net Generation (MW) from All Petroleum Products                               65209 non-null   float64
 20  Net Generation (MW) from Hydropower Excluding Pumped Storage                  135481 non-null  float64
 21  Net Generation (MW) from Pumped Storage                                       14781 non-null   float64
 22  Net Generation (MW) from Solar without Integrated Battery Storage             127321 non-null  float64
 23  Net Generation (MW) from Solar with Integrated Battery Storage                35655 non-null   float64
 24  Net Generation (MW) from Wind without Integrated Battery Storage              91646 non-null   float64
 25  Net Generation (MW) from Wind with Integrated Battery Storage                 2999 non-null    float64
 26  Net Generation (MW) from Battery Storage                                      52899 non-null   float64
 27  Net Generation (MW) from Other Energy Storage                                 5974 non-null    float64
 28  Net Generation (MW) from Unknown Energy Storage                               2986 non-null    float64
 29  Net Generation (MW) from Geothermal                                           14966 non-null   float64
 30  Net Generation (MW) from Other Fuel Sources                                   92481 non-null   float64
 31  Net Generation (MW) from Unknown Fuel Sources                                 2999 non-null    float64
 32  Net Generation (MW) from Coal (Imputed)                                       437 non-null     float64
 33  Net Generation (MW) from Natural Gas (Imputed)                                500 non-null     float64
 34  Net Generation (MW) from Nuclear (Imputed)                                    203 non-null     float64
 35  Net Generation (MW) from All Petroleum Products (Imputed)                     155 non-null     float64
 36  Net Generation (MW) from Hydropower Excluding Pumped Storage (Imputed)        406 non-null     float64
 37  Net Generation (MW) from Pumped Storage (Imputed)                             48 non-null      float64
 38  Net Generation (MW) from Solar without Integrated Battery Storage (Imputed)   481 non-null     float64
 39  Net Generation (MW) from Solar with Integrated Battery Storage (Imputed)      122 non-null     float64
 40  Net Generation (MW) from Wind without Integrated Battery Storage (Imputed)    484 non-null     float64
 41  Net Generation (MW) from Wind with Integrated Battery Storage (Imputed)       0 non-null       float64
 42  Net Generation (MW) from Battery Storage (Imputed)                            106 non-null     float64
 43  Net Generation (MW) from Other Energy Storage (Imputed)                       24 non-null      float64
 44  Net Generation (MW) from Unknown Energy Storage (Imputed)                     0 non-null       float64
 45  Net Generation (MW) from Geothermal (Imputed)                                 30 non-null      float64
 46  Net Generation (MW) from Other Fuel Sources (Imputed)                         272 non-null     float64
 47  Net Generation (MW) from Unknown Fuel Sources (Imputed)                       0 non-null       float64
 48  Net Generation (MW) from Coal (Adjusted)                                      100098 non-null  float64
 49  Net Generation (MW) from Natural Gas (Adjusted)                               145736 non-null  float64
 50  Net Generation (MW) from Nuclear (Adjusted)                                   53769 non-null   float64
 51  Net Generation (MW) from All Petroleum Products (Adjusted)                    65357 non-null   float64
 52  Net Generation (MW) from Hydropower Excluding Pumped Storage (Adjusted)       135876 non-null  float64
 53  Net Generation (MW) from Pumped Storage  (Adjusted)                           14829 non-null   float64
 54  Net Generation (MW) from Solar without Integrated Battery Storage (Adjusted)  127742 non-null  float64
 55  Net Generation (MW) from Solar witho Integrated Battery Storage (Adjusted)    35777 non-null   float64
 56  Net Generation (MW) from Wind without Integrated Battery Storage (Adjusted)   91969 non-null   float64
 57  Net Generation (MW) from Wind with Integrated Battery Storage (Adjusted)      2999 non-null    float64
 58  Net Generation (MW) from Battery Storage (Adjusted)                           53005 non-null   float64
 59  Net Generation (MW) from Other Energy Storage (Adjusted)                      5998 non-null    float64
 60  Net Generation (MW) from Unknown Energy Storage (Adjusted)                    2986 non-null    float64
 61  Net Generation (MW) from Geothermal (Adjusted)                                14996 non-null   float64
 62  Net Generation (MW) from Other Fuel Sources (Adjusted)                        92752 non-null   float64
 63  Net Generation (MW) from Unknown Fuel Sources (Adjusted)                      2999 non-null    float64
 64  Region                                                                        181222 non-null  object
dtypes: float64(59), int64(1), object(5)
memory usage: 89.9+ MB

## Interchange

In [26]:
df_interchange = pd.read_csv("Contoh dataset\EIA930_INTERCHANGE_2026_Jan_Jun.csv")
df_interchange.head()

,Balancing Authority,Data Date,Hour Number,Directly Interconnected Balancing Authority,Interchange (MW),Local Time at End of Hour,UTC Time at End of Hour,Region,DIBA_Region
0,AECI,01/01/2026,1,MISO,342.0,01/01/2026 1:00:00 AM,01/01/2026 7:00:00 AM,MIDW,MIDW
1,AECI,01/01/2026,1,SIKE,13.0,01/01/2026 1:00:00 AM,01/01/2026 7:00:00 AM,MIDW,MIDW
2,AECI,01/01/2026,1,SPA,-63.0,01/01/2026 1:00:00 AM,01/01/2026 7:00:00 AM,MIDW,CENT
3,AECI,01/01/2026,1,SWPP,-217.0,01/01/2026 1:00:00 AM,01/01/2026 7:00:00 AM,MIDW,CENT
4,AECI,01/01/2026,1,TVA,242.0,01/01/2026 1:00:00 AM,01/01/2026 7:00:00 AM,MIDW,TEN

In [27]:
df_interchange.columns

Index(['Balancing Authority', 'Data Date', 'Hour Number',
       'Directly Interconnected Balancing Authority', 'Interchange (MW)',
       'Local Time at End of Hour', 'UTC Time at End of Hour', 'Region',
       'DIBA_Region'],
      dtype='object')

In [28]:
# for numerical data
df_interchange.describe().to_csv('EksplorasiSingkat/balanced_numerical_description.csv')
df_interchange.describe()

         Hour Number  Interchange (MW)
count  889585.000000     848076.000000
mean       12.496910        -14.023102
std         6.920553        794.596327
min         1.000000    -327861.000000
25%         6.000000       -195.000000
50%        12.000000          0.000000
75%        18.000000        184.000000
max        24.000000      44735.000000

In [29]:
# for numerical data
df_interchange.describe(include="object").to_csv('EksplorasiSingkat/balanced_categorical_description.csv')
df_interchange.describe(include="object")

,Balancing Authority,Data Date,Directly Interconnected Balancing Authority,Local Time at End of Hour,UTC Time at End of Hour,Region,DIBA_Region
count,889585,889585,889585,889585,889585,889585,889585
unique,62,124,70,2976,2978,13,15
top,BPAT,01/01/2026,BPAT,01/01/2026 1:00:00 AM,04/01/2026 7:00:00 AM,NW,NW
freq,53550,7176,50575,299,306,289398,283453

In [30]:
balanced_info = pd.DataFrame({
    "column": df_interchange.columns,
    "non_null_count": df_interchange.notna().sum().values,
    "null_count": df_interchange.isna().sum().values,
    "dtype": df_interchange.dtypes.astype(str).values
})

balanced_info.to_csv("EksplorasiSingkat/balanced_info.csv", index=False)
df_interchange.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889585 entries, 0 to 889584
Data columns (total 9 columns):
 #   Column                                       Non-Null Count   Dtype
---  ------                                       --------------   -----
 0   Balancing Authority                          889585 non-null  object
 1   Data Date                                    889585 non-null  object
 2   Hour Number                                  889585 non-null  int64
 3   Directly Interconnected Balancing Authority  889585 non-null  object
 4   Interchange (MW)                             848076 non-null  float64
 5   Local Time at End of Hour                    889585 non-null  object
 6   UTC Time at End of Hour                      889585 non-null  object
 7   Region                                       889585 non-null  object
 8   DIBA_Region                                  889585 non-null  object
dtypes: float64(1), int64(1), object(7)
memory usage: 61.1+ MB

## Subregion

In [31]:
df_subregion = pd.read_csv("Contoh dataset\EIA930_SUBREGION_2026_Jan_Jun.csv")
df_subregion.head()

,Balancing Authority,Data Date,Hour Number,Sub-Region,Demand (MW),Local Time at End of Hour,UTC Time at End of Hour
0,BHBA,04/01/2026,1,BASI,245.0,04/01/2026 1:00:00 AM,04/01/2026 7:00:00 AM
1,BHBA,04/01/2026,1,SDE,258.0,04/01/2026 1:00:00 AM,04/01/2026 7:00:00 AM
2,BHBA,04/01/2026,1,WYE,312.0,04/01/2026 1:00:00 AM,04/01/2026 7:00:00 AM
3,BHBA,04/01/2026,2,BASI,247.0,04/01/2026 2:00:00 AM,04/01/2026 8:00:00 AM
4,BHBA,04/01/2026,2,SDE,255.0,04/01/2026 2:00:00 AM,04/01/2026 8:00:00 AM

In [32]:
df_subregion.columns

Index(['Balancing Authority', 'Data Date', 'Hour Number', 'Sub-Region',
       'Demand (MW)', 'Local Time at End of Hour', 'UTC Time at End of Hour'],
      dtype='object')

In [33]:
# for numerical data
df_subregion.describe().to_csv('EksplorasiSingkat/balanced_numerical_description.csv')
df_subregion.describe()

         Hour Number    Demand (MW)
count  253972.000000  245912.000000
mean       12.496921    3738.104554
std         6.920568    4611.641740
min         1.000000     -11.000000
25%         6.000000     780.000000
50%        12.000000    1838.000000
75%        18.000000    4552.000000
max        24.000000   29718.000000

In [34]:
# for numerical data
df_subregion.describe(include="object").to_csv('EksplorasiSingkat/balanced_categorical_description.csv')
df_subregion.describe(include="object")

,Balancing Authority,Data Date,Sub-Region,Local Time at End of Hour,UTC Time at End of Hour
count,253972,253972,253972,253972,253972
unique,10,125,89,3000,3002
top,PJM,04/01/2026,Jica,04/01/2026 1:00:00 AM,04/01/2026 7:00:00 AM
freq,59980,2136,3000,89,89

In [35]:
balanced_info = pd.DataFrame({
    "column": df_subregion.columns,
    "non_null_count": df_subregion.notna().sum().values,
    "null_count": df_subregion.isna().sum().values,
    "dtype": df_subregion.dtypes.astype(str).values
})

balanced_info.to_csv("EksplorasiSingkat/balanced_info.csv", index=False)
df_subregion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253972 entries, 0 to 253971
Data columns (total 7 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Balancing Authority        253972 non-null  object
 1   Data Date                  253972 non-null  object
 2   Hour Number                253972 non-null  int64
 3   Sub-Region                 253972 non-null  object
 4   Demand (MW)                245912 non-null  float64
 5   Local Time at End of Hour  253972 non-null  object
 6   UTC Time at End of Hour    253972 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 13.6+ MB

## FINAL: merge data balanced

# Data Cuaca

## Open-Meteo Historical Weather API

### Data historis

In [36]:
import requests
import pandas as pd

url = "https://archive-api.open-meteo.com/v1/archive"

params = {
    "latitude": 34.05,       # contoh: Los Angeles
    "longitude": -118.24,
    "start_date": "2024-01-01",
    "end_date": "2024-01-07",
    "hourly": [
        "temperature_2m",
        "relative_humidity_2m",
        "wind_speed_10m",
        "precipitation"
    ],
    "timezone": "UTC"
}

response = requests.get(url, params=params)
response.raise_for_status()

data = response.json()["hourly"]
weather_df = pd.DataFrame(data)

weather_df["time"] = pd.to_datetime(weather_df["time"])
weather_df.head()

,time,temperature_2m,relative_humidity_2m,wind_speed_10m,precipitation
0,2024-01-01 00:00:00,14.9,80,6.9,0.0
1,2024-01-01 01:00:00,14.8,72,1.8,0.0
2,2024-01-01 02:00:00,12.9,89,10.7,0.0
3,2024-01-01 03:00:00,11.6,92,8.7,0.0
4,2024-01-01 04:00:00,11.2,92,5.9,0.0

### forecast

In [37]:
import requests
import pandas as pd

def fetch_open_meteo_forecast(latitude, longitude, forecast_days=2):
    url = "https://api.open-meteo.com/v1/forecast"

    params = {
        "latitude": latitude,
        "longitude": longitude,
        "hourly": [
            "temperature_2m",
            "relative_humidity_2m",
            "wind_speed_10m",
            "precipitation"
        ],
        "forecast_days": forecast_days,
        "timezone": "UTC"
    }

    response = requests.get(url, params=params)
    response.raise_for_status()

    data = response.json()["hourly"]
    df = pd.DataFrame(data)
    df["time"] = pd.to_datetime(df["time"])

    return df

In [38]:
weather_forecast = fetch_open_meteo_forecast(
    latitude=34.05,
    longitude=-118.24,
    forecast_days=2
)

weather_forecast.head()

,time,temperature_2m,relative_humidity_2m,wind_speed_10m,precipitation
0,2026-05-07 00:00:00,21.5,57,15.5,0.0
1,2026-05-07 01:00:00,19.5,62,14.6,0.0
2,2026-05-07 02:00:00,18.6,63,12.8,0.0
3,2026-05-07 03:00:00,17.1,70,10.4,0.0
4,2026-05-07 04:00:00,15.9,81,5.4,0.0

# END