In [71]:
import pandas as pd
from glob import glob
import numpy as np

from pathlib import Path

In [3]:
dataset_paths = glob("electricity_dataset/*.csv")
dataset_paths

['electricity_dataset\\EIA930_BALANCE_2015_Jul_Dec.csv',
 'electricity_dataset\\EIA930_BALANCE_2016_Jan_Jun.csv',
 'electricity_dataset\\EIA930_BALANCE_2016_Jul_Dec.csv',
 'electricity_dataset\\EIA930_BALANCE_2017_Jan_Jun.csv',
 'electricity_dataset\\EIA930_BALANCE_2017_Jul_Dec.csv',
 'electricity_dataset\\EIA930_BALANCE_2018_Jan_Jun.csv',
 'electricity_dataset\\EIA930_BALANCE_2018_Jul_Dec.csv',
 'electricity_dataset\\EIA930_BALANCE_2019_Jan_Jun.csv',
 'electricity_dataset\\EIA930_BALANCE_2019_Jul_Dec.csv',
 'electricity_dataset\\EIA930_BALANCE_2020_Jan_Jun.csv',
 'electricity_dataset\\EIA930_BALANCE_2020_Jul_Dec.csv',
 'electricity_dataset\\EIA930_BALANCE_2021_Jan_Jun.csv',
 'electricity_dataset\\EIA930_BALANCE_2021_Jul_Dec.csv',
 'electricity_dataset\\EIA930_BALANCE_2022_Jan_Jun.csv',
 'electricity_dataset\\EIA930_BALANCE_2022_Jul_Dec.csv',
 'electricity_dataset\\EIA930_BALANCE_2023_Jan_Jun.csv',
 'electricity_dataset\\EIA930_BALANCE_2023_Jul_Dec.csv',
 'electricity_dataset\\EIA930_BALANCE_2024_Jan_Jun.csv',
 'electricity_dataset\\EIA930_BALANCE_2024_Jul_Dec.csv',
 'electricity_dataset\\EIA930_BALANCE_2025_Jan_Jun.csv',
 'electricity_dataset\\EIA930_BALANCE_2025_Jul_Dec.csv',
 'electricity_dataset\\EIA930_BALANCE_2026_Jan_Jun.csv']

In [15]:
pd.read_csv(dataset_paths[0]).head()

,Balancing Authority,Data Date,Hour Number,Local Time at End of Hour,UTC Time at End of Hour,Demand Forecast (MW),Demand (MW),Net Generation (MW),Total Interchange (MW),Sum(Valid DIBAs) (MW),Demand (MW) (Imputed),Net Generation (MW) (Imputed),Total Interchange (MW) (Imputed),Demand (MW) (Adjusted),Net Generation (MW) (Adjusted),Total Interchange (MW) (Adjusted),Net Generation (MW) from Unknown Fuel Sources (Imputed),Net Generation (MW) from Unknown Fuel Sources (Adjusted),Region
0,AEC,07/01/2015,1,07/01/2015 1:00:00 AM,07/01/2015 6:00:00 AM,882.0,422.0,670.0,248.0,248.0,NaN,NaN,NaN,422.0,670.0,248.0,NaN,NaN,SE
1,AEC,07/01/2015,2,07/01/2015 2:00:00 AM,07/01/2015 7:00:00 AM,819.0,395.0,620.0,225.0,225.0,NaN,NaN,NaN,395.0,620.0,225.0,NaN,NaN,SE
2,AEC,07/01/2015,3,07/01/2015 3:00:00 AM,07/01/2015 8:00:00 AM,782.0,382.0,637.0,255.0,255.0,NaN,NaN,NaN,382.0,637.0,255.0,NaN,NaN,SE
3,AEC,07/01/2015,4,07/01/2015 4:00:00 AM,07/01/2015 9:00:00 AM,763.0,370.0,619.0,249.0,249.0,NaN,NaN,NaN,370.0,619.0,249.0,NaN,NaN,SE
4,AEC,07/01/2015,5,07/01/2015 5:00:00 AM,07/01/2015 10:00:00 AM,774.0,383.0,633.0,250.0,250.0,NaN,NaN,NaN,383.0,633.0,250.0,NaN,NaN,SE

In [6]:
dfs = pd.DataFrame(columns=["dataset_path", "basename_file", "num_columns", "columns", "year", "start_month", "end_month", "semester", "num_rows"])

for dataset_path in dataset_paths:
    row = []

    df = pd.read_csv(dataset_path)
    basename_file = Path(dataset_path).stem

    year = basename_file.split("_")[2]
    start_month = basename_file.split("_")[-2]
    end_month = basename_file.split("_")[-1]
    semester = 1 if start_month.lower() == "jan" else 2

    dfs.loc[len(dfs)] = [
        dataset_path, 
        basename_file, 
        len(df.columns), 
        df.columns.tolist(), 
        year, 
        start_month, 
        end_month, 
        semester, 
        len(df)
    ]

dfs.to_csv("electricityEDA_outputs/electricity_dataset_summary.csv", index=False)
dfs.head()

,dataset_path,basename_file,num_columns,columns,year,start_month,end_month,semester,num_rows
0,electricity_dataset\EIA930_BALANCE_2015_Jul_De...,EIA930_BALANCE_2015_Jul_Dec,19,"[Balancing Authority, Data Date, Hour Number, ...",2015,Jul,Dec,2,293717
1,electricity_dataset\EIA930_BALANCE_2016_Jan_Ju...,EIA930_BALANCE_2016_Jan_Jun,19,"[Balancing Authority, Data Date, Hour Number, ...",2016,Jan,Jun,1,288235
2,electricity_dataset\EIA930_BALANCE_2016_Jul_De...,EIA930_BALANCE_2016_Jul_Dec,19,"[Balancing Authority, Data Date, Hour Number, ...",2016,Jul,Dec,2,291509
3,electricity_dataset\EIA930_BALANCE_2017_Jan_Ju...,EIA930_BALANCE_2017_Jan_Jun,19,"[Balancing Authority, Data Date, Hour Number, ...",2017,Jan,Jun,1,286651
4,electricity_dataset\EIA930_BALANCE_2017_Jul_De...,EIA930_BALANCE_2017_Jul_Dec,19,"[Balancing Authority, Data Date, Hour Number, ...",2017,Jul,Dec,2,291509

## Does all dataset have the same columns?

In [8]:
reference_columns = dfs.loc[0, "columns"]
dfs["same_columns_ignore_order"] = dfs["columns"].apply(lambda cols: set(cols) == set(reference_columns))

dfs[[
    "basename_file",
    "num_columns",
    "same_columns_ignore_order"
]]

                  basename_file  num_columns  same_columns_ignore_order
0   EIA930_BALANCE_2015_Jul_Dec           19                       True
1   EIA930_BALANCE_2016_Jan_Jun           19                       True
2   EIA930_BALANCE_2016_Jul_Dec           19                       True
3   EIA930_BALANCE_2017_Jan_Jun           19                       True
4   EIA930_BALANCE_2017_Jul_Dec           19                       True
5   EIA930_BALANCE_2018_Jan_Jun           19                       True
6   EIA930_BALANCE_2018_Jul_Dec           44                      False
7   EIA930_BALANCE_2019_Jan_Jun           44                      False
8   EIA930_BALANCE_2019_Jul_Dec           44                      False
9   EIA930_BALANCE_2020_Jan_Jun           44                      False
10  EIA930_BALANCE_2020_Jul_Dec           44                      False
11  EIA930_BALANCE_2021_Jan_Jun           44                      False
12  EIA930_BALANCE_2021_Jul_Dec           44                      False
13  EIA930_BALANCE_2022_Jan_Jun           44                      False
14  EIA930_BALANCE_2022_Jul_Dec           44                      False
15  EIA930_BALANCE_2023_Jan_Jun           44                      False
16  EIA930_BALANCE_2023_Jul_Dec           44                      False
17  EIA930_BALANCE_2024_Jan_Jun           44                      False
18  EIA930_BALANCE_2024_Jul_Dec           65                      False
19  EIA930_BALANCE_2025_Jan_Jun           65                      False
20  EIA930_BALANCE_2025_Jul_Dec           65                      False
21  EIA930_BALANCE_2026_Jan_Jun           65                      False

In [ ]:
# the minimum column we have (19 columns)
dfs.iloc[0]['columns']

['Balancing Authority',
 'Data Date',
 'Hour Number',
 'Local Time at End of Hour',
 'UTC Time at End of Hour',
 'Demand Forecast (MW)',
 'Demand (MW)',
 'Net Generation (MW)',
 'Total Interchange (MW)',
 'Sum(Valid DIBAs) (MW)',
 'Demand (MW) (Imputed)',
 'Net Generation (MW) (Imputed)',
 'Total Interchange (MW) (Imputed)',
 'Demand (MW) (Adjusted)',
 'Net Generation (MW) (Adjusted)',
 'Total Interchange (MW) (Adjusted)',
 'Net Generation (MW) from Unknown Fuel Sources (Imputed)',
 'Net Generation (MW) from Unknown Fuel Sources (Adjusted)',
 'Region']

In [13]:
# Check if all datasets have at least the 19 columns from the first dataset
base_columns = dfs.loc[0, "columns"]
base_set = set(base_columns)

dfs["has_all_base_19_columns"] = dfs["columns"].apply(
    lambda cols: base_set.issubset(set(cols))
)

dfs[[
    "basename_file",
    "num_columns",
    "has_all_base_19_columns"
]]

                  basename_file  num_columns  has_all_base_19_columns
0   EIA930_BALANCE_2015_Jul_Dec           19                     True
1   EIA930_BALANCE_2016_Jan_Jun           19                     True
2   EIA930_BALANCE_2016_Jul_Dec           19                     True
3   EIA930_BALANCE_2017_Jan_Jun           19                     True
4   EIA930_BALANCE_2017_Jul_Dec           19                     True
5   EIA930_BALANCE_2018_Jan_Jun           19                     True
6   EIA930_BALANCE_2018_Jul_Dec           44                     True
7   EIA930_BALANCE_2019_Jan_Jun           44                     True
8   EIA930_BALANCE_2019_Jul_Dec           44                     True
9   EIA930_BALANCE_2020_Jan_Jun           44                     True
10  EIA930_BALANCE_2020_Jul_Dec           44                     True
11  EIA930_BALANCE_2021_Jan_Jun           44                     True
12  EIA930_BALANCE_2021_Jul_Dec           44                     True
13  EIA930_BALANCE_2022_Jan_Jun           44                     True
14  EIA930_BALANCE_2022_Jul_Dec           44                     True
15  EIA930_BALANCE_2023_Jan_Jun           44                     True
16  EIA930_BALANCE_2023_Jul_Dec           44                     True
17  EIA930_BALANCE_2024_Jan_Jun           44                     True
18  EIA930_BALANCE_2024_Jul_Dec           65                     True
19  EIA930_BALANCE_2025_Jan_Jun           65                     True
20  EIA930_BALANCE_2025_Jul_Dec           65                     True
21  EIA930_BALANCE_2026_Jan_Jun           65                     True

## Check missing values

### Yes, there are missing values in the target variable **Demand (MW)**, can we impute it based on other candidate target variables?

---

Short answer: No, even in mostly cases the there are no difference between Demand (MW) and Demand (MW) Adjusted, but the min and max differences values show us that there are extreme difference. Due to this situation, we think it is best for us to use other approaches to impute the missing values.

note: imputed data will only use for training purposes, for testing it will not be used.

In [ ]:
keep_modeling_cols = [
    'Data Date',
    'Hour Number',
    'Local Time at End of Hour',
    'UTC Time at End of Hour',
    'Demand (MW)',
    'Demand (MW) (Imputed)',
    'Demand (MW) (Adjusted)',
    'Region'
]

df_merge = pd.DataFrame(columns=keep_modeling_cols)

for dataset_path in dataset_paths:
    df = pd.read_csv(dataset_path)
    df = df[keep_modeling_cols]
    df_merge = pd.concat([df_merge, df], ignore_index=True)

print(f"dataset size: {df_merge.shape}")
print()
df_merge.head()

C:\Users\surya\AppData\Local\Temp\ipykernel_21544\3265855880.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_merge = pd.concat([df_merge, df], ignore_index=True)

dataset size: (6056162, 8)

,Data Date,Hour Number,Local Time at End of Hour,UTC Time at End of Hour,Demand (MW),Demand (MW) (Imputed),Demand (MW) (Adjusted),Region
0,07/01/2015,1,07/01/2015 1:00:00 AM,07/01/2015 6:00:00 AM,422.0,NaN,422.0,SE
1,07/01/2015,2,07/01/2015 2:00:00 AM,07/01/2015 7:00:00 AM,395.0,NaN,395.0,SE
2,07/01/2015,3,07/01/2015 3:00:00 AM,07/01/2015 8:00:00 AM,382.0,NaN,382.0,SE
3,07/01/2015,4,07/01/2015 4:00:00 AM,07/01/2015 9:00:00 AM,370.0,NaN,370.0,SE
4,07/01/2015,5,07/01/2015 5:00:00 AM,07/01/2015 10:00:00 AM,383.0,NaN,383.0,SE

In [34]:
missing_values = df_merge.isnull().sum()
print("Missing values in each column:")
print(missing_values)

Missing values in each column:
Data Date                          0
Hour Number                        0
Local Time at End of Hour          0
UTC Time at End of Hour            0
Demand (MW)                   954018
Demand (MW) (Imputed)        6023183
Demand (MW) (Adjusted)        930973
Region                             0
dtype: int64

In [28]:
mask_original_missing_adjusted_available = (
    df_merge["Demand (MW)"].isna() &
    df_merge["Demand (MW) (Adjusted)"].notna()
)

print(mask_original_missing_adjusted_available.sum())

mask_original_available_adjusted_missing = (
    df_merge["Demand (MW)"].notna() &
    df_merge["Demand (MW) (Adjusted)"].isna()
)

print(mask_original_available_adjusted_missing.sum())

23045
0

In [30]:
both_available = df_merge[
    df_merge["Demand (MW)"].notna() &
    df_merge["Demand (MW) (Adjusted)"].notna()
].copy()

both_available["diff"] = (
    both_available["Demand (MW) (Adjusted)"] - both_available["Demand (MW)"]
)

both_available["diff"].describe()

count    5.102144e+06
mean    -7.600362e+02
std      1.183505e+06
min     -2.147410e+09
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      9.993649e+07
Name: diff, dtype: float64

In [32]:
both_available = df_merge[
    df_merge["Demand (MW)"].notna() &
    df_merge["Demand (MW) (Adjusted)"].notna()
].copy()

both_available["diff"] = (
    both_available["Demand (MW) (Adjusted)"] - both_available["Demand (MW)"]
)

diff_rows = both_available[both_available["diff"] != 0]

print("Rows both available:", len(both_available))
print("Rows with different adjusted:", len(diff_rows))
print("Percentage different:", len(diff_rows) / len(both_available) * 100)

Rows both available: 5102144
Rows with different adjusted: 9934
Percentage different: 0.19470246233740168

### Missing value -> imputation

In [ ]:
import os
from pathlib import Path

import pandas as pd
import numpy as np

os.makedirs("electricityEDA_outputs", exist_ok=True)

keep_cols = [
    "Balancing Authority",
    "Data Date",
    "Hour Number",
    "Local Time at End of Hour",
    "UTC Time at End of Hour",
    "Demand (MW)",
    "Demand Forecast (MW)",
    "Region"
]

all_dfs = []

for dataset_path in dataset_paths:
    df = pd.read_csv(dataset_path)

    existing_cols = [col for col in keep_cols if col in df.columns]
    temp = df[existing_cols].copy()

    temp["source_file"] = Path(dataset_path).stem
    all_dfs.append(temp)

df_merge = pd.concat(all_dfs, ignore_index=True)

df_merge["timestamp_utc"] = pd.to_datetime(
    df_merge["UTC Time at End of Hour"],
    errors="coerce",
    utc=True
)

df_merge["data_date"] = pd.to_datetime(
    df_merge["Data Date"],
    errors="coerce"
)

df_merge["Demand (MW)"] = pd.to_numeric(
    df_merge["Demand (MW)"],
    errors="coerce"
)

df_merge["Demand Forecast (MW)"] = pd.to_numeric(
    df_merge["Demand Forecast (MW)"],
    errors="coerce"
)

df_merge["Hour Number"] = pd.to_numeric(
    df_merge["Hour Number"],
    errors="coerce"
)

warmup_start_date = pd.Timestamp("2015-07-01")
modeling_start_date = pd.Timestamp("2017-07-01")
train_end_date = pd.Timestamp("2024-01-01")
valid_end_date = pd.Timestamp("2025-01-01")
test_end_date = pd.Timestamp("2026-05-07")  

df_merge_clipped = df_merge[
    (df_merge["data_date"] >= warmup_start_date) &
    (df_merge["data_date"] < test_end_date)
].copy()

df_merge_clipped = df_merge_clipped.sort_values(
    ["Balancing Authority", "timestamp_utc"]
).reset_index(drop=True)

print("Shape:", df_merge_clipped.shape)
print("Local date range:", df_merge_clipped["data_date"].min(), "to", df_merge_clipped["data_date"].max())
print("UTC range:", df_merge_clipped["timestamp_utc"].min(), "to", df_merge_clipped["timestamp_utc"].max())
print("Regions:", sorted(df_merge_clipped["Region"].dropna().unique()))
print("Number of Balancing Authorities:", df_merge_clipped["Balancing Authority"].nunique())

df_merge_clipped.head()

Shape: (6056162, 11)
Local date range: 2015-07-01 00:00:00 to 2026-05-06 00:00:00
UTC range: 2015-07-01 05:00:00+00:00 to 2026-05-07 07:00:00+00:00
Regions: ['CAL', 'CAR', 'CENT', 'FLA', 'MIDA', 'MIDW', 'NE', 'NW', 'NY', 'SE', 'SW', 'TEN', 'TEX']
Number of Balancing Authorities: 72

,Balancing Authority,Data Date,Hour Number,Local Time at End of Hour,UTC Time at End of Hour,Demand (MW),Demand Forecast (MW),Region,source_file,timestamp_utc,data_date
0,AEC,07/01/2015,1,07/01/2015 1:00:00 AM,07/01/2015 6:00:00 AM,422.0,882.0,SE,EIA930_BALANCE_2015_Jul_Dec,2015-07-01 06:00:00+00:00,2015-07-01
1,AEC,07/01/2015,2,07/01/2015 2:00:00 AM,07/01/2015 7:00:00 AM,395.0,819.0,SE,EIA930_BALANCE_2015_Jul_Dec,2015-07-01 07:00:00+00:00,2015-07-01
2,AEC,07/01/2015,3,07/01/2015 3:00:00 AM,07/01/2015 8:00:00 AM,382.0,782.0,SE,EIA930_BALANCE_2015_Jul_Dec,2015-07-01 08:00:00+00:00,2015-07-01
3,AEC,07/01/2015,4,07/01/2015 4:00:00 AM,07/01/2015 9:00:00 AM,370.0,763.0,SE,EIA930_BALANCE_2015_Jul_Dec,2015-07-01 09:00:00+00:00,2015-07-01
4,AEC,07/01/2015,5,07/01/2015 5:00:00 AM,07/01/2015 10:00:00 AM,383.0,774.0,SE,EIA930_BALANCE_2015_Jul_Dec,2015-07-01 10:00:00+00:00,2015-07-01

In [ ]:
missing_by_region = (
    df_merge
    .groupby("Region")["Demand (MW)"]
    .apply(lambda x: x.isna().mean() * 100)
    .reset_index(name="missing_demand_pct")
    .sort_values("missing_demand_pct", ascending=False)
)

# some regions has more missing values than others, which may be due to different data collection practices or issues in those regions.
missing_by_region

   Region  missing_demand_pct
9      SE           39.710024
10     SW           33.314172
5    MIDW           20.033508
7      NW           19.250602
1     CAR           17.426855
4    MIDA            5.575230
2    CENT            1.419379
3     FLA            1.279396
0     CAL            0.476911
12    TEX            0.328034
11    TEN            0.324880
6      NE            0.031542
8      NY            0.025233

In [ ]:
df_merge["UTC Time at End of Hour"] = pd.to_datetime(df_merge["UTC Time at End of Hour"], errors="coerce")
df_merge["year"] = df_merge["UTC Time at End of Hour"].dt.year

missing_by_year = (
    df_merge
    .groupby("year")["Demand (MW)"]
    .apply(lambda x: x.isna().mean() * 100)
    .reset_index(name="missing_demand_pct")
)

# percentage of missing demand values mostly decreasing over the years, but still cannot derive anything for imputation/drop strategy.
missing_by_year

    year  missing_demand_pct
0   2015           19.883775
1   2016           16.740147
2   2017           16.210219
3   2018           17.192666
4   2019           15.922374
5   2020           17.685072
6   2021           15.910908
7   2022           15.578787
8   2023           14.369609
9   2024           13.201910
10  2025           12.877682
11  2026           13.518244

In [ ]:
missing_region_year = (
    df_merge
    .groupby(["Region", "year"])["Demand (MW)"]
    .apply(lambda x: x.isna().mean() * 100)
    .reset_index(name="missing_demand_pct")
    .sort_values("missing_demand_pct", ascending=False)
)

# very high missing percentage in some region-year combinations -> raises concern about imputation based on "region + hour + day_of_week"
missing_region_year.head(30)

    Region  year  missing_demand_pct
119     SE  2026           50.596421
118     SE  2025           50.000000
117     SE  2024           50.000000
116     SE  2023           50.000000
115     SE  2022           50.000000
120     SW  2015           40.873412
121     SW  2016           40.457650
122     SW  2017           40.030822
108     SE  2015           38.601663
114     SE  2021           37.503211
123     SW  2018           37.020642
111     SE  2018           35.133181
110     SE  2017           34.615677
126     SW  2021           34.372146
109     SE  2016           34.247875
112     SE  2019           33.725266
124     SW  2019           33.639016
125     SW  2020           33.429468
113     SE  2020           33.420613
127     SW  2022           33.334602
128     SW  2023           32.173317
71    MIDW  2026           25.520833
65    MIDW  2020           25.213456
66    MIDW  2021           25.176941
64    MIDW  2019           25.154110
60    MIDW  2015           25.136054
129     SW  2024           25.102459
63    MIDW  2018           25.068493
62    MIDW  2017           25.034247
61    MIDW  2016           25.031307

### is it possible to be imputed?

In [40]:
df_merge["timestamp"] = pd.to_datetime(df_merge["UTC Time at End of Hour"], errors="coerce")

df_merge["year"] = df_merge["timestamp"].dt.year
df_merge["hour"] = df_merge["timestamp"].dt.hour
df_merge["day_of_week"] = df_merge["timestamp"].dt.dayofweek

group_quality = (
    df_merge
    .groupby(["Region", "year", "day_of_week", "hour"])["Demand (MW)"]
    .agg(
        total_count="size",
        valid_count=lambda x: x.notna().sum(),
        missing_count=lambda x: x.isna().sum(),
        missing_pct=lambda x: x.isna().mean() * 100,
        mean_demand="mean"
    )
    .reset_index()
)

group_quality.head()

,Region,year,day_of_week,hour,total_count,valid_count,missing_count,missing_pct,mean_demand
0,CAL,2015,0,0,130,128,2,1.538462,7378.054688
1,CAL,2015,0,1,130,128,2,1.538462,7517.671875
2,CAL,2015,0,2,130,128,2,1.538462,7668.656250
3,CAL,2015,0,3,130,128,2,1.538462,7829.273438
4,CAL,2015,0,4,130,128,2,1.538462,7778.507812

In [41]:
min_valid_count = 10

group_quality["is_reliable_group"] = group_quality["valid_count"] >= min_valid_count
group_quality["is_reliable_group"].value_counts(normalize=True) * 100

is_reliable_group
True    100.0
Name: proportion, dtype: float64

In [42]:
unreliable_groups = group_quality[~group_quality["is_reliable_group"]]
unreliable_groups.sort_values("valid_count").head(20)

Empty DataFrame
Columns: [Region, year, day_of_week, hour, total_count, valid_count, missing_count, missing_pct, mean_demand, is_reliable_group]
Index: []

In [43]:
reliability_region_year = (
    group_quality
    .groupby(["Region", "year"])
    .agg(
        total_groups=("is_reliable_group", "size"),
        reliable_groups=("is_reliable_group", "sum")
    )
    .reset_index()
)

reliability_region_year["reliable_group_pct"] = (
    reliability_region_year["reliable_groups"] /
    reliability_region_year["total_groups"] * 100
)

reliability_region_year.sort_values("reliable_group_pct").head(30)

    Region  year  total_groups  reliable_groups  reliable_group_pct
0      CAL  2015           168              168               100.0
100     NY  2019           168              168               100.0
101     NY  2020           168              168               100.0
102     NY  2021           168              168               100.0
103     NY  2022           168              168               100.0
104     NY  2023           168              168               100.0
105     NY  2024           168              168               100.0
106     NY  2025           168              168               100.0
107     NY  2026           168              168               100.0
108     SE  2015           168              168               100.0
109     SE  2016           168              168               100.0
110     SE  2017           168              168               100.0
111     SE  2018           168              168               100.0
112     SE  2019           168              168               100.0
113     SE  2020           168              168               100.0
114     SE  2021           168              168               100.0
99      NY  2018           168              168               100.0
98      NY  2017           168              168               100.0
97      NY  2016           168              168               100.0
96      NY  2015           168              168               100.0
80      NE  2023           168              168               100.0
81      NE  2024           168              168               100.0
82      NE  2025           168              168               100.0
83      NE  2026           168              168               100.0
84      NW  2015           168              168               100.0
85      NW  2016           168              168               100.0
86      NW  2017           168              168               100.0
115     SE  2022           168              168               100.0
87      NW  2018           168              168               100.0
89      NW  2020           168              168               100.0

### Proses imputasi dilakukan

--- 

Imputasi dilakukan dengan mengambil nilai mean dari region yang sama + day of week yang sama + hour yang sama dari rentang waktu 2 tahun sebelum hari H. Selain itu, karena dataset yang tersedia berukuran besar dan untuk simplicity dalam imputasi, maka dataset 2015H2 s.d. 2017H1 dijadikan sumber imputasi, 2017H2 s.d. 2023H2 (training), dan 2024H1 s.d. 2026H2 (validasi).

In [55]:
keep_modeling_cols = [
    "Data Date",
    "Hour Number",
    "Local Time at End of Hour",
    "UTC Time at End of Hour",
    "Demand (MW)",
    "Region"
]

all_dfs = []

for dataset_path in dataset_paths:
    df = pd.read_csv(dataset_path)

    existing_cols = [col for col in keep_modeling_cols if col in df.columns]
    temp = df[existing_cols].copy()

    temp["source_file"] = Path(dataset_path).stem

    all_dfs.append(temp)

df_merge = pd.concat(all_dfs, ignore_index=True)

# Convert timestamp
df_merge["timestamp_utc"] = pd.to_datetime(
    df_merge["UTC Time at End of Hour"],
    errors="coerce",
    utc=True
)

# Convert target to numeric
df_merge["Demand (MW)"] = pd.to_numeric(df_merge["Demand (MW)"], errors="coerce")

# Periode:
# 2015H2–2017H1 = warm-up/lookback only
# 2017H2–2026H1 = modeling period
warmup_start_date = pd.Timestamp("2015-07-01", tz="UTC")
modeling_start_date = pd.Timestamp("2017-07-01", tz="UTC")
end_date = pd.Timestamp("2026-07-01", tz="UTC")  # exclusive, sampai 2026-06-30

df_merge_clipped = df_merge[
    (df_merge["timestamp_utc"] >= warmup_start_date) &
    (df_merge["timestamp_utc"] < end_date)
].copy()

df_merge_clipped = df_merge_clipped.sort_values(
    ["Region", "timestamp_utc"]
).reset_index(drop=True)

df_merge_clipped["is_modeling_period"] = (
    df_merge_clipped["timestamp_utc"] >= modeling_start_date
).astype(int)

print("Warm-up + modeling dataset size:", df_merge_clipped.shape)
print("Time range:", df_merge_clipped["timestamp_utc"].min(), "to", df_merge_clipped["timestamp_utc"].max())
print("Modeling start:", modeling_start_date)
print("Regions:", df_merge_clipped["Region"].unique())

df_merge_clipped.head()

Warm-up + modeling dataset size: (6056162, 9)
Time range: 2015-07-01 05:00:00+00:00 to 2026-05-07 07:00:00+00:00
Modeling start: 2017-07-01 00:00:00+00:00
Regions: ['CAL' 'CAR' 'CENT' 'FLA' 'MIDA' 'MIDW' 'NE' 'NW' 'NY' 'SE' 'SW' 'TEN'
 'TEX']

,Data Date,Hour Number,Local Time at End of Hour,UTC Time at End of Hour,Demand (MW),Region,source_file,timestamp_utc,is_modeling_period
0,07/01/2015,1,07/01/2015 1:00:00 AM,07/01/2015 8:00:00 AM,2513.0,CAL,EIA930_BALANCE_2015_Jul_Dec,2015-07-01 08:00:00+00:00,0
1,07/01/2015,1,07/01/2015 1:00:00 AM,07/01/2015 8:00:00 AM,31486.0,CAL,EIA930_BALANCE_2015_Jul_Dec,2015-07-01 08:00:00+00:00,0
2,07/01/2015,1,07/01/2015 1:00:00 AM,07/01/2015 8:00:00 AM,505.0,CAL,EIA930_BALANCE_2015_Jul_Dec,2015-07-01 08:00:00+00:00,0
3,07/01/2015,1,07/01/2015 1:00:00 AM,07/01/2015 8:00:00 AM,3298.0,CAL,EIA930_BALANCE_2015_Jul_Dec,2015-07-01 08:00:00+00:00,0
4,07/01/2015,1,07/01/2015 1:00:00 AM,07/01/2015 8:00:00 AM,408.0,CAL,EIA930_BALANCE_2015_Jul_Dec,2015-07-01 08:00:00+00:00,0

In [56]:
missing_summary = df_merge_clipped.isna().sum().reset_index()
missing_summary.columns = ["column", "missing_count"]
missing_summary["missing_pct"] = missing_summary["missing_count"] / len(df_merge_clipped) * 100

missing_summary

                      column  missing_count  missing_pct
0                  Data Date              0     0.000000
1                Hour Number              0     0.000000
2  Local Time at End of Hour              0     0.000000
3    UTC Time at End of Hour              0     0.000000
4                Demand (MW)         954018    15.752848
5                     Region              0     0.000000
6                source_file              0     0.000000
7              timestamp_utc              0     0.000000
8         is_modeling_period              0     0.000000

In [57]:
missing_by_region_all = (
    df_merge_clipped
    .groupby("Region")["Demand (MW)"]
    .apply(lambda x: x.isna().mean() * 100)
    .reset_index(name="missing_demand_pct_all_period")
    .sort_values("missing_demand_pct_all_period", ascending=False)
)

missing_by_region_modeling = (
    df_merge_clipped[df_merge_clipped["is_modeling_period"] == 1]
    .groupby("Region")["Demand (MW)"]
    .apply(lambda x: x.isna().mean() * 100)
    .reset_index(name="missing_demand_pct_modeling_period")
    .sort_values("missing_demand_pct_modeling_period", ascending=False)
)

missing_by_region_compare = missing_by_region_all.merge(
    missing_by_region_modeling,
    on="Region",
    how="left"
)

missing_by_region_compare.sort_values(
    "missing_demand_pct_modeling_period",
    ascending=False
)

   Region  missing_demand_pct_all_period  missing_demand_pct_modeling_period
0      SE                      39.710024                           40.895859
1      SW                      33.314172                           31.461529
3      NW                      19.250602                           19.399330
2    MIDW                      20.033508                           18.799620
4     CAR                      17.426855                           17.582840
6    CENT                       1.419379                            1.724805
7     FLA                       1.279396                            0.972834
8     CAL                       0.476911                            0.451170
5    MIDA                       5.575230                            0.425504
9     TEX                       0.328034                            0.216567
10    TEN                       0.324880                            0.122464
11     NE                       0.031542                            0.034806
12     NY                       0.025233                            0.030939

In [ ]:
def make_complete_hourly_ba(group):
    ba = group["Balancing Authority"].iloc[0]
    region = group["Region"].dropna().iloc[0] if group["Region"].notna().any() else np.nan

    group = group.sort_values("timestamp_utc").drop_duplicates("timestamp_utc")
    group = group.set_index("timestamp_utc")

    full_index = pd.date_range(
        start=group.index.min(),
        end=group.index.max(),
        freq="h",
        tz="UTC"
    )

    group = group.reindex(full_index)
    group.index.name = "timestamp_utc"

    group["Balancing Authority"] = ba
    group["Region"] = region

    return group.reset_index()


df_complete_ba = (
    df_merge_clipped
    .groupby("Balancing Authority", group_keys=False)
    .apply(make_complete_hourly_ba)
    .reset_index(drop=True)
)

df_complete_ba = df_complete_ba.sort_values(
    ["Balancing Authority", "timestamp_utc"]
).reset_index(drop=True)

print("BA-level complete hourly shape:", df_complete_ba.shape)
print("Number of BAs:", df_complete_ba["Balancing Authority"].nunique())

df_complete_ba.head()

C:\Users\surya\AppData\Local\Temp\ipykernel_21544\432302022.py:25: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(make_complete_hourly)

Complete hourly dataset size: (1236457, 9)

,timestamp_utc,Data Date,Hour Number,Local Time at End of Hour,UTC Time at End of Hour,Demand (MW),Region,source_file,is_modeling_period
0,2015-07-01 08:00:00+00:00,07/01/2015,1,07/01/2015 1:00:00 AM,07/01/2015 8:00:00 AM,2513.0,CAL,EIA930_BALANCE_2015_Jul_Dec,0
1,2015-07-01 09:00:00+00:00,07/01/2015,2,07/01/2015 2:00:00 AM,07/01/2015 9:00:00 AM,2275.0,CAL,EIA930_BALANCE_2015_Jul_Dec,0
2,2015-07-01 10:00:00+00:00,07/01/2015,3,07/01/2015 3:00:00 AM,07/01/2015 10:00:00 AM,357.0,CAL,EIA930_BALANCE_2015_Jul_Dec,0
3,2015-07-01 11:00:00+00:00,07/01/2015,4,07/01/2015 4:00:00 AM,07/01/2015 11:00:00 AM,1988.0,CAL,EIA930_BALANCE_2015_Jul_Dec,0
4,2015-07-01 12:00:00+00:00,07/01/2015,5,07/01/2015 5:00:00 AM,07/01/2015 12:00:00 PM,1958.0,CAL,EIA930_BALANCE_2015_Jul_Dec,0

In [ ]:
df_complete_ba["year"] = df_complete_ba["timestamp_utc"].dt.year
df_complete_ba["month"] = df_complete_ba["timestamp_utc"].dt.month
df_complete_ba["utc_hour"] = df_complete_ba["timestamp_utc"].dt.hour
df_complete_ba["day_of_week"] = df_complete_ba["timestamp_utc"].dt.dayofweek

# Untuk sementara pakai utc_hour sebagai hour grouping.
# Nanti untuk calendar feature final, sebaiknya pakai local time / region timezone.
df_complete_ba["hour"] = df_complete_ba["utc_hour"]

df_complete_ba.head()

,timestamp_utc,Data Date,Hour Number,Local Time at End of Hour,UTC Time at End of Hour,Demand (MW),Region,source_file,is_modeling_period,year,month,hour,day_of_week,is_weekend
0,2015-07-01 08:00:00+00:00,07/01/2015,1,07/01/2015 1:00:00 AM,07/01/2015 8:00:00 AM,2513.0,CAL,EIA930_BALANCE_2015_Jul_Dec,0,2015,7,8,2,0
1,2015-07-01 09:00:00+00:00,07/01/2015,2,07/01/2015 2:00:00 AM,07/01/2015 9:00:00 AM,2275.0,CAL,EIA930_BALANCE_2015_Jul_Dec,0,2015,7,9,2,0
2,2015-07-01 10:00:00+00:00,07/01/2015,3,07/01/2015 3:00:00 AM,07/01/2015 10:00:00 AM,357.0,CAL,EIA930_BALANCE_2015_Jul_Dec,0,2015,7,10,2,0
3,2015-07-01 11:00:00+00:00,07/01/2015,4,07/01/2015 4:00:00 AM,07/01/2015 11:00:00 AM,1988.0,CAL,EIA930_BALANCE_2015_Jul_Dec,0,2015,7,11,2,0
4,2015-07-01 12:00:00+00:00,07/01/2015,5,07/01/2015 5:00:00 AM,07/01/2015 12:00:00 PM,1958.0,CAL,EIA930_BALANCE_2015_Jul_Dec,0,2015,7,12,2,0

In [60]:
def causal_impute_demand_2y_no_fallback(
    df,
    target_col="Demand (MW)",
    region_col="Region",
    time_col="timestamp_utc",
    min_group_count=5,
    lookback_years=2
):
    df = df.copy()
    df = df.sort_values([region_col, time_col]).reset_index(drop=True)

    df["target_demand_mw"] = df[target_col]
    df["is_target_imputed"] = 0
    df["imputation_method"] = "observed"

    result_parts = []

    for region, g in df.groupby(region_col):
        g = g.copy().sort_values(time_col).reset_index(drop=True)

        missing_indices = g.index[g["target_demand_mw"].isna()]

        for idx in missing_indices:
            current_time = g.loc[idx, time_col]
            current_hour = g.loc[idx, "hour"]
            current_dow = g.loc[idx, "day_of_week"]

            lookback_start = current_time - pd.DateOffset(years=lookback_years)

            hist_group = g[
                (g[time_col] < current_time) &
                (g[time_col] >= lookback_start) &
                (g[target_col].notna()) &
                (g["hour"] == current_hour) &
                (g["day_of_week"] == current_dow)
            ]

            if len(hist_group) >= min_group_count:
                g.loc[idx, "target_demand_mw"] = hist_group[target_col].mean()
                g.loc[idx, "is_target_imputed"] = 1
                g.loc[idx, "imputation_method"] = "region_dow_hour_prev2y"
            else:
                g.loc[idx, "imputation_method"] = "not_imputed"

        result_parts.append(g)

    out = pd.concat(result_parts, ignore_index=True)
    out = out.sort_values([region_col, time_col]).reset_index(drop=True)

    return out

In [ ]:
warmup_start_date = pd.Timestamp("2015-07-01", tz="UTC")
modeling_start_date = pd.Timestamp("2017-07-01", tz="UTC")

train_end_date = pd.Timestamp("2024-01-01", tz="UTC")  # train sampai 2023-12-31 23:00
valid_end_date = pd.Timestamp("2025-01-01", tz="UTC")  # valid sepanjang 2024
test_end_date = pd.Timestamp("2026-05-07", tz="UTC")

threshold_results = []

for min_count in [5, 10, 15, 20, 30]:
    temp = causal_impute_demand_2y_no_fallback(
        df_complete,
        target_col="Demand (MW)",
        region_col="Region",
        time_col="timestamp_utc",
        min_group_count=min_count,
        lookback_years=2
    )

    # Validation/test tidak boleh pakai target hasil imputasi
    eval_mask = temp["timestamp_utc"] >= train_end_date
    temp.loc[eval_mask, "target_demand_mw"] = temp.loc[eval_mask, "Demand (MW)"]
    temp.loc[eval_mask, "is_target_imputed"] = 0
    temp.loc[eval_mask, "imputation_method"] = np.where(
        temp.loc[eval_mask, "Demand (MW)"].notna(),
        "observed_eval_period",
        "missing_eval_period_not_imputed"
    )

    train_mask = (
        (temp["timestamp_utc"] >= modeling_start_date) &
        (temp["timestamp_utc"] < train_end_date)
    )

    valid_mask = (
        (temp["timestamp_utc"] >= train_end_date) &
        (temp["timestamp_utc"] < valid_end_date)
    )

    test_mask = (
        (temp["timestamp_utc"] >= valid_end_date) &
        (temp["timestamp_utc"] < test_end_date)
    )

    threshold_results.append({
        "min_group_count": min_count,
        "train_remaining_missing": temp.loc[train_mask, "target_demand_mw"].isna().sum(),
        "train_imputed_rows": temp.loc[train_mask, "is_target_imputed"].sum(),
        "valid_actual_missing": temp.loc[valid_mask, "Demand (MW)"].isna().sum(),
        "test_actual_missing": temp.loc[test_mask, "Demand (MW)"].isna().sum(),
    })

threshold_results_df = pd.DataFrame(threshold_results)
threshold_results_df

KeyboardInterrupt:

In [ ]:
FINAL_MIN_GROUP_COUNT = 5

df_imputed_ba = causal_impute_demand_2y_no_fallback(
    df_complete_ba,
    target_col="Demand (MW)",
    region_col="Balancing Authority",
    time_col="timestamp_utc",
    min_group_count=FINAL_MIN_GROUP_COUNT,
    lookback_years=2
)

# Validation/test tidak boleh target-imputed untuk evaluasi.
# Karena ini masih BA-level, kita kembalikan target_demand_mw ke actual Demand untuk eval period.
eval_mask = df_imputed_ba["data_date"] >= train_end_date

df_imputed_ba.loc[eval_mask, "target_demand_mw"] = df_imputed_ba.loc[
    eval_mask, "Demand (MW)"
]

df_imputed_ba.loc[eval_mask, "is_target_imputed"] = 0

df_imputed_ba.loc[eval_mask, "imputation_method"] = np.where(
    df_imputed_ba.loc[eval_mask, "Demand (MW)"].notna(),
    "observed_eval_period",
    "missing_eval_period_not_imputed"
)

print("Original missing BA demand:", df_complete_ba["Demand (MW)"].isna().sum())
print("After BA causal imputation:", df_imputed_ba["target_demand_mw"].isna().sum())
print("Imputed BA rows:", df_imputed_ba["is_target_imputed"].sum())

display(df_imputed_ba["imputation_method"].value_counts())

Original missing target: 88397
After causal imputation: 1598
Imputed rows: 86799

imputation_method
observed                  1148060
region_dow_hour_prev2y      86799
not_imputed                  1598
Name: count, dtype: int64

In [ ]:
def count_missing(x):
    return x.isna().sum()

def count_notna(x):
    return x.notna().sum()

df_region_hourly = (
    df_imputed_ba
    .groupby(["Region", "timestamp_utc"], as_index=False)
    .agg(
        data_date=("data_date", "min"),

        # Target actual region demand.
        # Ini hanya reliable kalau semua BA demand actual tersedia.
        actual_region_demand_mw=("Demand (MW)", "sum"),

        # Target final untuk training/lag history.
        # Ini boleh berisi BA-level imputation pada train period.
        target_region_demand_mw=("target_demand_mw", "sum"),

        # Demand Forecast sebagai benchmark eksternal, bukan fitur.
        demand_forecast_mw=("Demand Forecast (MW)", "sum"),

        num_ba=("Balancing Authority", "nunique"),
        num_rows=("Balancing Authority", "size"),
        num_actual_missing_ba=("Demand (MW)", count_missing),
        num_actual_available_ba=("Demand (MW)", count_notna),
        num_imputed_ba=("is_target_imputed", "sum")
    )
)

# Kalau semua BA actual missing pada timestamp itu, sum bisa jadi 0.
# Kita ubah actual_region_demand_mw jadi NaN jika tidak ada actual demand sama sekali.
df_region_hourly.loc[
    df_region_hourly["num_actual_available_ba"] == 0,
    "actual_region_demand_mw"
] = np.nan

# Flag apakah actual region total reliable untuk evaluation.
# Strict rule: semua BA dalam region-hour harus punya actual Demand.
df_region_hourly["is_actual_region_complete"] = (
    df_region_hourly["num_actual_missing_ba"] == 0
).astype(int)

# Kalau target_region_demand_mw tidak punya komponen sama sekali, set NaN
# Biasanya jarang, tapi untuk safety.
df_region_hourly.loc[
    df_region_hourly["target_region_demand_mw"] == 0,
    "target_region_demand_mw"
] = np.nan

df_region_hourly = df_region_hourly.sort_values(
    ["Region", "timestamp_utc"]
).reset_index(drop=True)

print("Region-level hourly shape:", df_region_hourly.shape)
print("Regions:", sorted(df_region_hourly["Region"].unique()))
display(df_region_hourly.head())

In [ ]:
duplicate_check = (
    df_region_hourly
    .groupby(["Region", "timestamp_utc"])
    .size()
    .reset_index(name="count")
)

print("Max rows per Region + timestamp:", duplicate_check["count"].max())

region_range_check = (
    df_region_hourly
    .groupby("Region")
    .agg(
        min_timestamp=("timestamp_utc", "min"),
        max_timestamp=("timestamp_utc", "max"),
        n_rows=("timestamp_utc", "size"),
        n_unique_timestamps=("timestamp_utc", "nunique"),
        actual_complete_pct=("is_actual_region_complete", lambda x: x.mean() * 100),
        total_imputed_ba=("num_imputed_ba", "sum")
    )
    .reset_index()
)

display(region_range_check)

In [ ]:
df_warmup_region = df_region_hourly[
    (df_region_hourly["data_date"] >= warmup_start_date) &
    (df_region_hourly["data_date"] < modeling_start_date)
].copy()

df_train_region_full = df_region_hourly[
    (df_region_hourly["data_date"] >= modeling_start_date) &
    (df_region_hourly["data_date"] < train_end_date)
].copy()

df_valid_region_full = df_region_hourly[
    (df_region_hourly["data_date"] >= train_end_date) &
    (df_region_hourly["data_date"] < valid_end_date)
].copy()

df_test_region_full = df_region_hourly[
    (df_region_hourly["data_date"] >= valid_end_date) &
    (df_region_hourly["data_date"] < test_end_date)
].copy()

# Train boleh pakai target_region_demand_mw.
df_train_region = df_train_region_full.dropna(
    subset=["target_region_demand_mw"]
).copy()

# Valid/test evaluasi hanya pada actual complete region demand.
df_valid_region = df_valid_region_full[
    df_valid_region_full["is_actual_region_complete"] == 1
].dropna(subset=["actual_region_demand_mw"]).copy()

df_test_region = df_test_region_full[
    df_test_region_full["is_actual_region_complete"] == 1
].dropna(subset=["actual_region_demand_mw"]).copy()

print("Warmup region:", df_warmup_region.shape)
print("Train region full:", df_train_region_full.shape, "| usable:", df_train_region.shape)
print("Valid region full:", df_valid_region_full.shape, "| actual complete:", df_valid_region.shape)
print("Test region full:", df_test_region_full.shape, "| actual complete:", df_test_region.shape)

In [ ]:
output_dir = "electricityEDA_outputs/reproducibility"
os.makedirs(output_dir, exist_ok=True)

df_imputed_ba.to_csv(
    f"{output_dir}/ba_level_after_causal_imputation.csv",
    index=False
)

df_region_hourly.to_csv(
    f"{output_dir}/region_hourly_aggregated_after_ba_imputation.csv",
    index=False
)

df_warmup_region.to_csv(
    f"{output_dir}/region_warmup_2015H2_2017H1.csv",
    index=False
)

df_train_region.to_csv(
    f"{output_dir}/region_train_usable_2017H2_2023H2.csv",
    index=False
)

df_valid_region.to_csv(
    f"{output_dir}/region_valid_actual_complete_2024.csv",
    index=False
)

df_test_region.to_csv(
    f"{output_dir}/region_test_actual_complete_2025_2026May.csv",
    index=False
)

print("Saved region-level files to:", output_dir)

# Testing

In [ ]:
# import pandas as pd

# # Pastikan timestamp sudah datetime UTC
# df_check_time = df_complete.copy()
# df_check_time["timestamp_utc"] = pd.to_datetime(
#     df_check_time["timestamp_utc"],
#     errors="coerce",
#     utc=True
# )

# print("=" * 70)
# print("GLOBAL TIME RANGE")
# print("=" * 70)
# print("Min timestamp:", df_check_time["timestamp_utc"].min())
# print("Max timestamp:", df_check_time["timestamp_utc"].max())

# print("\nUnique hours:")
# print(sorted(df_check_time["timestamp_utc"].dt.hour.dropna().unique()))

# print("\nHour count:")
# display(
#     df_check_time["timestamp_utc"]
#     .dt.hour
#     .value_counts()
#     .sort_index()
#     .rename_axis("hour")
#     .reset_index(name="count")
# )

# print("\n" + "=" * 70)
# print("TIME RANGE BY REGION")
# print("=" * 70)

# range_by_region = (
#     df_check_time
#     .groupby("Region")
#     .agg(
#         min_timestamp=("timestamp_utc", "min"),
#         max_timestamp=("timestamp_utc", "max"),
#         n_rows=("timestamp_utc", "size"),
#         n_unique_timestamps=("timestamp_utc", "nunique")
#     )
#     .reset_index()
# )

# range_by_region["min_hour"] = range_by_region["min_timestamp"].dt.hour
# range_by_region["max_hour"] = range_by_region["max_timestamp"].dt.hour

# display(range_by_region)

# print("\n" + "=" * 70)
# print("EXPECTED PERIOD CHECK")
# print("=" * 70)

# expected_start = pd.Timestamp("2015-07-01 00:00:00", tz="UTC")
# expected_modeling_start = pd.Timestamp("2017-07-01 00:00:00", tz="UTC")
# expected_train_end_exclusive = pd.Timestamp("2024-01-01 00:00:00", tz="UTC")
# expected_valid_end_exclusive = pd.Timestamp("2025-01-01 00:00:00", tz="UTC")
# expected_test_end_exclusive = pd.Timestamp("2026-07-01 00:00:00", tz="UTC")
# expected_last_timestamp = expected_test_end_exclusive - pd.Timedelta(hours=1)

# print("Expected warmup start:        ", expected_start)
# print("Expected modeling start:      ", expected_modeling_start)
# print("Expected train end exclusive: ", expected_train_end_exclusive)
# print("Expected valid end exclusive: ", expected_valid_end_exclusive)
# print("Expected test end exclusive:  ", expected_test_end_exclusive)
# print("Expected last timestamp:      ", expected_last_timestamp)

# print("\nActual starts at expected warmup start?")
# print(df_check_time["timestamp_utc"].min() == expected_start)

# print("\nActual ends at expected last timestamp?")
# print(df_check_time["timestamp_utc"].max() == expected_last_timestamp)

# print("\nDoes final timestamp hour equal 23?")
# print(df_check_time["timestamp_utc"].max().hour == 23)

# print("\n" + "=" * 70)
# print("PERIOD ROW COUNTS")
# print("=" * 70)

# period_summary = pd.DataFrame([
#     {
#         "period": "warmup",
#         "start_inclusive": expected_start,
#         "end_exclusive": expected_modeling_start,
#         "rows": ((df_check_time["timestamp_utc"] >= expected_start) &
#                  (df_check_time["timestamp_utc"] < expected_modeling_start)).sum()
#     },
#     {
#         "period": "train",
#         "start_inclusive": expected_modeling_start,
#         "end_exclusive": expected_train_end_exclusive,
#         "rows": ((df_check_time["timestamp_utc"] >= expected_modeling_start) &
#                  (df_check_time["timestamp_utc"] < expected_train_end_exclusive)).sum()
#     },
#     {
#         "period": "validation",
#         "start_inclusive": expected_train_end_exclusive,
#         "end_exclusive": expected_valid_end_exclusive,
#         "rows": ((df_check_time["timestamp_utc"] >= expected_train_end_exclusive) &
#                  (df_check_time["timestamp_utc"] < expected_valid_end_exclusive)).sum()
#     },
#     {
#         "period": "test",
#         "start_inclusive": expected_valid_end_exclusive,
#         "end_exclusive": expected_test_end_exclusive,
#         "rows": ((df_check_time["timestamp_utc"] >= expected_valid_end_exclusive) &
#                  (df_check_time["timestamp_utc"] < expected_test_end_exclusive)).sum()
#     }
# ])

# display(period_summary)

# print("\n" + "=" * 70)
# print("CHECK LAST DAY HOURS")
# print("=" * 70)

# last_date = df_check_time["timestamp_utc"].max().date()

# last_day_hours = (
#     df_check_time[df_check_time["timestamp_utc"].dt.date == last_date]
#     .assign(hour=lambda x: x["timestamp_utc"].dt.hour)
#     .groupby("Region")["hour"]
#     .apply(lambda x: sorted(x.unique()))
#     .reset_index(name="hours_on_last_day")
# )

# display(last_day_hours)

# print("\nIf hours_on_last_day contains 0 through 23 for each region, then the last day is complete.")

======================================================================
GLOBAL TIME RANGE
======================================================================
Min timestamp: 2015-07-01 05:00:00+00:00
Max timestamp: 2026-05-07 07:00:00+00:00

Unique hours:
[np.int32(0), np.int32(1), np.int32(2), np.int32(3), np.int32(4), np.int32(5), np.int32(6), np.int32(7), np.int32(8), np.int32(9), np.int32(10), np.int32(11), np.int32(12), np.int32(13), np.int32(14), np.int32(15), np.int32(16), np.int32(17), np.int32(18), np.int32(19), np.int32(20), np.int32(21), np.int32(22), np.int32(23)]

Hour count:

    hour  count
0      0  51519
1      1  51519
2      2  51519
3      3  51519
4      4  51519
5      5  51519
6      6  51519
7      7  51520
8      8  51519
9      9  51519
10    10  51519
11    11  51519
12    12  51519
13    13  51519
14    14  51519
15    15  51519
16    16  51519
17    17  51519
18    18  51519
19    19  51519
20    20  51519
21    21  51519
22    22  51519
23    23  51519

======================================================================
TIME RANGE BY REGION
======================================================================

,Region,min_timestamp,max_timestamp,n_rows,n_unique_timestamps,min_hour,max_hour
0,CAL,2015-07-01 08:00:00+00:00,2026-05-07 07:00:00+00:00,95112,95112,8,7
1,CAR,2015-07-01 05:00:00+00:00,2026-05-07 04:00:00+00:00,95112,95112,5,4
2,CENT,2015-07-01 06:00:00+00:00,2026-05-07 05:00:00+00:00,95112,95112,6,5
3,FLA,2015-07-01 05:00:00+00:00,2026-05-07 04:00:00+00:00,95112,95112,5,4
4,MIDA,2015-07-01 05:00:00+00:00,2026-05-07 04:00:00+00:00,95112,95112,5,4
5,MIDW,2015-07-01 06:00:00+00:00,2026-05-07 05:00:00+00:00,95112,95112,6,5
6,NE,2015-07-01 05:00:00+00:00,2026-05-07 04:00:00+00:00,95112,95112,5,4
7,NW,2015-07-01 07:00:00+00:00,2026-05-07 07:00:00+00:00,95113,95113,7,7
8,NY,2015-07-01 05:00:00+00:00,2026-05-07 04:00:00+00:00,95112,95112,5,4
9,SE,2015-07-01 06:00:00+00:00,2026-05-07 05:00:00+00:00,95112,95112,6,5
10,SW,2015-07-01 08:00:00+00:00,2026-05-07 07:00:00+00:00,95112,95112,8,7
11,TEN,2015-07-01 06:00:00+00:00,2026-05-07 05:00:00+00:00,95112,95112,6,5
12,TEX,2015-07-01 06:00:00+00:00,2026-05-07 05:00:00+00:00,95112,95112,6,5

======================================================================
EXPECTED PERIOD CHECK
======================================================================
Expected warmup start:         2015-07-01 00:00:00+00:00
Expected modeling start:       2017-07-01 00:00:00+00:00
Expected train end exclusive:  2024-01-01 00:00:00+00:00
Expected valid end exclusive:  2025-01-01 00:00:00+00:00
Expected test end exclusive:   2026-07-01 00:00:00+00:00
Expected last timestamp:       2026-06-30 23:00:00+00:00

Actual starts at expected warmup start?
False

Actual ends at expected last timestamp?
False

Does final timestamp hour equal 23?
False

======================================================================
PERIOD ROW COUNTS
======================================================================

       period           start_inclusive             end_exclusive    rows
0      warmup 2015-07-01 00:00:00+00:00 2017-07-01 00:00:00+00:00  227994
1       train 2017-07-01 00:00:00+00:00 2024-01-01 00:00:00+00:00  741000
2  validation 2024-01-01 00:00:00+00:00 2025-01-01 00:00:00+00:00  114192
3        test 2025-01-01 00:00:00+00:00 2026-07-01 00:00:00+00:00  153271

======================================================================
CHECK LAST DAY HOURS
======================================================================

   Region         hours_on_last_day
0     CAL  [0, 1, 2, 3, 4, 5, 6, 7]
1     CAR           [0, 1, 2, 3, 4]
2    CENT        [0, 1, 2, 3, 4, 5]
3     FLA           [0, 1, 2, 3, 4]
4    MIDA           [0, 1, 2, 3, 4]
5    MIDW        [0, 1, 2, 3, 4, 5]
6      NE           [0, 1, 2, 3, 4]
7      NW  [0, 1, 2, 3, 4, 5, 6, 7]
8      NY           [0, 1, 2, 3, 4]
9      SE        [0, 1, 2, 3, 4, 5]
10     SW  [0, 1, 2, 3, 4, 5, 6, 7]
11    TEN        [0, 1, 2, 3, 4, 5]
12    TEX        [0, 1, 2, 3, 4, 5]

If hours_on_last_day contains 0 through 23 for each region, then the last day is complete.

In [ ]:
# import pandas as pd
# import numpy as np

# # Pilih dataframe yang ingin dicek
# # Kalau kamu sudah punya df_merge_clipped, pakai itu.
# # Kalau ingin cek setelah complete hourly, bisa ganti ke df_complete.
# df_time_check = df_merge_clipped.copy()

# # Convert date/time
# df_time_check["data_date"] = pd.to_datetime(df_time_check["Data Date"], errors="coerce")
# df_time_check["timestamp_utc"] = pd.to_datetime(
#     df_time_check["timestamp_utc"],
#     errors="coerce",
#     utc=True
# )

# # Pastikan Hour Number numeric
# df_time_check["Hour Number"] = pd.to_numeric(
#     df_time_check["Hour Number"],
#     errors="coerce"
# )

# print("=" * 80)
# print("BASIC RANGE CHECK")
# print("=" * 80)

# print("Local Data Date range:")
# print(df_time_check["data_date"].min(), "to", df_time_check["data_date"].max())

# print("\nUTC timestamp range:")
# print(df_time_check["timestamp_utc"].min(), "to", df_time_check["timestamp_utc"].max())

# print("\nRegions:")
# print(sorted(df_time_check["Region"].dropna().unique()))

# print("\nHour Number unique values:")
# print(sorted(df_time_check["Hour Number"].dropna().unique()))

# print("\nUTC hour unique values:")
# print(sorted(df_time_check["timestamp_utc"].dt.hour.dropna().unique()))


# print("\n" + "=" * 80)
# print("LOCAL DATE COMPLETENESS CHECK: 24 HOURS PER REGION-DATE")
# print("=" * 80)

# daily_hour_check = (
#     df_time_check
#     .groupby(["Region", "data_date"])
#     .agg(
#         row_count=("Hour Number", "size"),
#         unique_hour_numbers=("Hour Number", "nunique"),
#         min_hour_number=("Hour Number", "min"),
#         max_hour_number=("Hour Number", "max"),
#         min_utc=("timestamp_utc", "min"),
#         max_utc=("timestamp_utc", "max")
#     )
#     .reset_index()
# )

# daily_hour_check["is_complete_24h"] = (
#     (daily_hour_check["unique_hour_numbers"] == 24) &
#     (daily_hour_check["row_count"] == 24)
# )

# summary_complete = (
#     daily_hour_check["is_complete_24h"]
#     .value_counts()
#     .rename_axis("is_complete_24h")
#     .reset_index(name="num_region_days")
# )

# display(summary_complete)

# incomplete_days = daily_hour_check[~daily_hour_check["is_complete_24h"]].copy()

# print("\nTotal incomplete region-days:", len(incomplete_days))

# if len(incomplete_days) > 0:
#     print("\nIncomplete days by region:")
#     display(
#         incomplete_days
#         .groupby("Region")
#         .size()
#         .reset_index(name="num_incomplete_days")
#         .sort_values("num_incomplete_days", ascending=False)
#     )

#     print("\nFirst 30 incomplete region-days:")
#     display(
#         incomplete_days
#         .sort_values(["data_date", "Region"])
#         .head(30)
#     )

#     print("\nLast 30 incomplete region-days:")
#     display(
#         incomplete_days
#         .sort_values(["data_date", "Region"])
#         .tail(30)
#     )


# print("\n" + "=" * 80)
# print("CHECK WHETHER INCOMPLETE DAYS ARE ONLY AT DATASET EDGES")
# print("=" * 80)

# edge_check = []

# for region, g in daily_hour_check.groupby("Region"):
#     region_min_date = g["data_date"].min()
#     region_max_date = g["data_date"].max()

#     inc = g[~g["is_complete_24h"]].copy()

#     if len(inc) == 0:
#         edge_check.append({
#             "Region": region,
#             "region_min_date": region_min_date,
#             "region_max_date": region_max_date,
#             "num_incomplete_days": 0,
#             "incomplete_only_edges": True,
#             "incomplete_dates_sample": []
#         })
#         continue

#     edge_dates = {region_min_date, region_max_date}
#     incomplete_dates = set(inc["data_date"])

#     incomplete_only_edges = incomplete_dates.issubset(edge_dates)

#     edge_check.append({
#         "Region": region,
#         "region_min_date": region_min_date,
#         "region_max_date": region_max_date,
#         "num_incomplete_days": len(inc),
#         "incomplete_only_edges": incomplete_only_edges,
#         "incomplete_dates_sample": sorted(list(incomplete_dates))[:10]
#     })

# edge_check_df = pd.DataFrame(edge_check)

# display(edge_check_df)


# print("\n" + "=" * 80)
# print("FULL LOCAL DATE RANGE BY REGION")
# print("=" * 80)

# range_by_region_local = (
#     df_time_check
#     .groupby("Region")
#     .agg(
#         min_data_date=("data_date", "min"),
#         max_data_date=("data_date", "max"),
#         min_utc=("timestamp_utc", "min"),
#         max_utc=("timestamp_utc", "max"),
#         n_rows=("timestamp_utc", "size"),
#         n_unique_utc=("timestamp_utc", "nunique")
#     )
#     .reset_index()
# )

# display(range_by_region_local)


# print("\n" + "=" * 80)
# print("RECOMMENDED LOCAL-DATE CUTOFF")
# print("=" * 80)

# # Cari local date terakhir yang complete untuk semua region
# complete_by_date = (
#     daily_hour_check
#     .groupby("data_date")["is_complete_24h"]
#     .all()
#     .reset_index(name="complete_for_all_regions")
# )

# last_complete_date_all_regions = complete_by_date.loc[
#     complete_by_date["complete_for_all_regions"],
#     "data_date"
# ].max()

# first_complete_date_all_regions = complete_by_date.loc[
#     complete_by_date["complete_for_all_regions"],
#     "data_date"
# ].min()

# print("First local date complete for all regions:", first_complete_date_all_regions)
# print("Last local date complete for all regions:", last_complete_date_all_regions)

# print("\nIf you split by Data Date, use an exclusive test_end_date one day after the last complete date:")
# if pd.notna(last_complete_date_all_regions):
#     recommended_test_end_date = last_complete_date_all_regions + pd.Timedelta(days=1)
#     print("recommended_test_end_date =", recommended_test_end_date)
# else:
#     print("No complete local date found for all regions.")

================================================================================
BASIC RANGE CHECK
================================================================================
Local Data Date range:
2015-07-01 00:00:00 to 2026-05-06 00:00:00

UTC timestamp range:
2015-07-01 05:00:00+00:00 to 2026-05-07 07:00:00+00:00

Regions:
['CAL', 'CAR', 'CENT', 'FLA', 'MIDA', 'MIDW', 'NE', 'NW', 'NY', 'SE', 'SW', 'TEN', 'TEX']

Hour Number unique values:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25)]

UTC hour unique values:
[np.int32(0), np.int32(1), np.int32(2), np.int32(3), np.int32(4), np.int32(5), np.int32(6), np.int32(7), np.int32(8), np.int32(9), np.int32(10), np.int32(11), np.int32(12), np.int32(13), np.int32(14), np.int32(15), np.int32(16), np.int32(17), np.int32(18), np.int32(19), np.int32(20), np.int32(21), np.int32(22), np.int32(23)]

================================================================================
LOCAL DATE COMPLETENESS CHECK: 24 HOURS PER REGION-DATE
================================================================================

   is_complete_24h  num_region_days
0            False            33055
1             True            18464

Total incomplete region-days: 33055

Incomplete days by region:

   Region  num_incomplete_days
0     CAL                 3963
1     CAR                 3963
2    CENT                 3963
3     FLA                 3963
5    MIDW                 3963
7      NW                 3963
10     SW                 3963
9      SE                 3962
4    MIDA                 1264
6      NE                   22
8      NY                   22
11    TEN                   22
12    TEX                   22

First 30 incomplete region-days:

,Region,data_date,row_count,unique_hour_numbers,min_hour_number,max_hour_number,min_utc,max_utc,is_complete_24h
0,CAL,2015-07-01,120,24,1,24,2015-07-01 08:00:00+00:00,2015-07-02 07:00:00+00:00,False
3963,CAR,2015-07-01,144,24,1,24,2015-07-01 05:00:00+00:00,2015-07-02 04:00:00+00:00,False
7926,CENT,2015-07-01,48,24,1,24,2015-07-01 06:00:00+00:00,2015-07-02 05:00:00+00:00,False
11889,FLA,2015-07-01,240,24,1,24,2015-07-01 05:00:00+00:00,2015-07-02 04:00:00+00:00,False
15852,MIDA,2015-07-01,48,24,1,24,2015-07-01 05:00:00+00:00,2015-07-02 04:00:00+00:00,False
19815,MIDW,2015-07-01,96,24,1,24,2015-07-01 06:00:00+00:00,2015-07-02 05:00:00+00:00,False
27741,NW,2015-07-01,504,24,1,24,2015-07-01 07:00:00+00:00,2015-07-02 07:00:00+00:00,False
35667,SE,2015-07-01,72,24,1,24,2015-07-01 06:00:00+00:00,2015-07-02 05:00:00+00:00,False
39630,SW,2015-07-01,240,24,1,24,2015-07-01 08:00:00+00:00,2015-07-02 07:00:00+00:00,False
1,CAL,2015-07-02,120,24,1,24,2015-07-02 08:00:00+00:00,2015-07-03 07:00:00+00:00,False
3964,CAR,2015-07-02,144,24,1,24,2015-07-02 05:00:00+00:00,2015-07-03 04:00:00+00:00,False
7927,CENT,2015-07-02,48,24,1,24,2015-07-02 06:00:00+00:00,2015-07-03 05:00:00+00:00,False
11890,FLA,2015-07-02,240,24,1,24,2015-07-02 05:00:00+00:00,2015-07-03 04:00:00+00:00,False
15853,MIDA,2015-07-02,48,24,1,24,2015-07-02 05:00:00+00:00,2015-07-03 04:00:00+00:00,False
19816,MIDW,2015-07-02,96,24,1,24,2015-07-02 06:00:00+00:00,2015-07-03 05:00:00+00:00,False
27742,NW,2015-07-02,504,24,1,24,2015-07-02 07:00:00+00:00,2015-07-03 07:00:00+00:00,False
35668,SE,2015-07-02,72,24,1,24,2015-07-02 06:00:00+00:00,2015-07-03 05:00:00+00:00,False
39631,SW,2015-07-02,240,24,1,24,2015-07-02 08:00:00+00:00,2015-07-03 07:00:00+00:00,False
2,CAL,2015-07-03,120,24,1,24,2015-07-03 08:00:00+00:00,2015-07-04 07:00:00+00:00,False
3965,CAR,2015-07-03,144,24,1,24,2015-07-03 05:00:00+00:00,2015-07-04 04:00:00+00:00,False
7928,CENT,2015-07-03,48,24,1,24,2015-07-03 06:00:00+00:00,2015-07-04 05:00:00+00:00,False
11891,FLA,2015-07-03,240,24,1,24,2015-07-03 05:00:00+00:00,2015-07-04 04:00:00+00:00,False
15854,MIDA,2015-07-03,48,24,1,24,2015-07-03 05:00:00+00:00,2015-07-04 04:00:00+00:00,False
19817,MIDW,2015-07-03,96,24,1,24,2015-07-03 06:00:00+00:00,2015-07-04 05:00:00+00:00,False
27743,NW,2015-07-03,504,24,1,24,2015-07-03 07:00:00+00:00,2015-07-04 07:00:00+00:00,False
35669,SE,2015-07-03,72,24,1,24,2015-07-03 06:00:00+00:00,2015-07-04 05:00:00+00:00,False
39632,SW,2015-07-03,240,24,1,24,2015-07-03 08:00:00+00:00,2015-07-04 07:00:00+00:00,False
3,CAL,2015-07-04,120,24,1,24,2015-07-04 08:00:00+00:00,2015-07-05 07:00:00+00:00,False
3966,CAR,2015-07-04,144,24,1,24,2015-07-04 05:00:00+00:00,2015-07-05 04:00:00+00:00,False
7929,CENT,2015-07-04,48,24,1,24,2015-07-04 06:00:00+00:00,2015-07-05 05:00:00+00:00,False

Last 30 incomplete region-days:

,Region,data_date,row_count,unique_hour_numbers,min_hour_number,max_hour_number,min_utc,max_utc,is_complete_24h
7922,CAR,2026-05-03,144,24,1,24,2026-05-03 05:00:00+00:00,2026-05-04 04:00:00+00:00,False
11885,CENT,2026-05-03,48,24,1,24,2026-05-03 06:00:00+00:00,2026-05-04 05:00:00+00:00,False
15848,FLA,2026-05-03,216,24,1,24,2026-05-03 05:00:00+00:00,2026-05-04 04:00:00+00:00,False
23774,MIDW,2026-05-03,96,24,1,24,2026-05-03 06:00:00+00:00,2026-05-04 05:00:00+00:00,False
31700,NW,2026-05-03,480,24,1,24,2026-05-03 06:00:00+00:00,2026-05-04 07:00:00+00:00,False
39626,SE,2026-05-03,48,24,1,24,2026-05-03 06:00:00+00:00,2026-05-04 05:00:00+00:00,False
43589,SW,2026-05-03,168,24,1,24,2026-05-03 08:00:00+00:00,2026-05-04 07:00:00+00:00,False
3960,CAL,2026-05-04,120,24,1,24,2026-05-04 08:00:00+00:00,2026-05-05 07:00:00+00:00,False
7923,CAR,2026-05-04,144,24,1,24,2026-05-04 05:00:00+00:00,2026-05-05 04:00:00+00:00,False
11886,CENT,2026-05-04,48,24,1,24,2026-05-04 06:00:00+00:00,2026-05-05 05:00:00+00:00,False
15849,FLA,2026-05-04,216,24,1,24,2026-05-04 05:00:00+00:00,2026-05-05 04:00:00+00:00,False
23775,MIDW,2026-05-04,96,24,1,24,2026-05-04 06:00:00+00:00,2026-05-05 05:00:00+00:00,False
31701,NW,2026-05-04,480,24,1,24,2026-05-04 06:00:00+00:00,2026-05-05 07:00:00+00:00,False
39627,SE,2026-05-04,48,24,1,24,2026-05-04 06:00:00+00:00,2026-05-05 05:00:00+00:00,False
43590,SW,2026-05-04,168,24,1,24,2026-05-04 08:00:00+00:00,2026-05-05 07:00:00+00:00,False
3961,CAL,2026-05-05,120,24,1,24,2026-05-05 08:00:00+00:00,2026-05-06 07:00:00+00:00,False
7924,CAR,2026-05-05,144,24,1,24,2026-05-05 05:00:00+00:00,2026-05-06 04:00:00+00:00,False
11887,CENT,2026-05-05,48,24,1,24,2026-05-05 06:00:00+00:00,2026-05-06 05:00:00+00:00,False
15850,FLA,2026-05-05,216,24,1,24,2026-05-05 05:00:00+00:00,2026-05-06 04:00:00+00:00,False
23776,MIDW,2026-05-05,96,24,1,24,2026-05-05 06:00:00+00:00,2026-05-06 05:00:00+00:00,False
31702,NW,2026-05-05,480,24,1,24,2026-05-05 06:00:00+00:00,2026-05-06 07:00:00+00:00,False
39628,SE,2026-05-05,48,24,1,24,2026-05-05 06:00:00+00:00,2026-05-06 05:00:00+00:00,False
43591,SW,2026-05-05,168,24,1,24,2026-05-05 08:00:00+00:00,2026-05-06 07:00:00+00:00,False
3962,CAL,2026-05-06,120,24,1,24,2026-05-06 08:00:00+00:00,2026-05-07 07:00:00+00:00,False
7925,CAR,2026-05-06,120,24,1,24,2026-05-06 05:00:00+00:00,2026-05-07 04:00:00+00:00,False
11888,CENT,2026-05-06,48,24,1,24,2026-05-06 06:00:00+00:00,2026-05-07 05:00:00+00:00,False
15851,FLA,2026-05-06,216,24,1,24,2026-05-06 05:00:00+00:00,2026-05-07 04:00:00+00:00,False
23777,MIDW,2026-05-06,72,24,1,24,2026-05-06 06:00:00+00:00,2026-05-07 05:00:00+00:00,False
31703,NW,2026-05-06,408,24,1,24,2026-05-06 06:00:00+00:00,2026-05-07 07:00:00+00:00,False
43592,SW,2026-05-06,144,24,1,24,2026-05-06 08:00:00+00:00,2026-05-07 07:00:00+00:00,False

================================================================================
CHECK WHETHER INCOMPLETE DAYS ARE ONLY AT DATASET EDGES
================================================================================

,Region,region_min_date,region_max_date,num_incomplete_days,incomplete_only_edges,incomplete_dates_sample
0,CAL,2015-07-01,2026-05-06,3963,False,"[2015-07-01 00:00:00, 2015-07-02 00:00:00, 201..."
1,CAR,2015-07-01,2026-05-06,3963,False,"[2015-07-01 00:00:00, 2015-07-02 00:00:00, 201..."
2,CENT,2015-07-01,2026-05-06,3963,False,"[2015-07-01 00:00:00, 2015-07-02 00:00:00, 201..."
3,FLA,2015-07-01,2026-05-06,3963,False,"[2015-07-01 00:00:00, 2015-07-02 00:00:00, 201..."
4,MIDA,2015-07-01,2026-05-06,1264,False,"[2015-07-01 00:00:00, 2015-07-02 00:00:00, 201..."
5,MIDW,2015-07-01,2026-05-06,3963,False,"[2015-07-01 00:00:00, 2015-07-02 00:00:00, 201..."
6,NE,2015-07-01,2026-05-06,22,False,"[2015-11-01 00:00:00, 2016-03-13 00:00:00, 201..."
7,NW,2015-07-01,2026-05-06,3963,False,"[2015-07-01 00:00:00, 2015-07-02 00:00:00, 201..."
8,NY,2015-07-01,2026-05-06,22,False,"[2015-11-01 00:00:00, 2016-03-13 00:00:00, 201..."
9,SE,2015-07-01,2026-05-06,3962,False,"[2015-07-01 00:00:00, 2015-07-02 00:00:00, 201..."
10,SW,2015-07-01,2026-05-06,3963,False,"[2015-07-01 00:00:00, 2015-07-02 00:00:00, 201..."
11,TEN,2015-07-01,2026-05-06,22,False,"[2015-11-01 00:00:00, 2016-03-13 00:00:00, 201..."
12,TEX,2015-07-01,2026-05-06,22,False,"[2015-11-01 00:00:00, 2016-03-13 00:00:00, 201..."

================================================================================
FULL LOCAL DATE RANGE BY REGION
================================================================================

,Region,min_data_date,max_data_date,min_utc,max_utc,n_rows,n_unique_utc
0,CAL,2015-07-01,2026-05-06,2015-07-01 08:00:00+00:00,2026-05-07 07:00:00+00:00,475560,95112
1,CAR,2015-07-01,2026-05-06,2015-07-01 05:00:00+00:00,2026-05-07 04:00:00+00:00,570648,95112
2,CENT,2015-07-01,2026-05-06,2015-07-01 06:00:00+00:00,2026-05-07 05:00:00+00:00,190224,95112
3,FLA,2015-07-01,2026-05-06,2015-07-01 05:00:00+00:00,2026-05-07 04:00:00+00:00,895657,95112
4,MIDA,2015-07-01,2026-05-06,2015-07-01 05:00:00+00:00,2026-05-07 04:00:00+00:00,125089,95112
5,MIDW,2015-07-01,2026-05-06,2015-07-01 06:00:00+00:00,2026-05-07 05:00:00+00:00,356328,95112
6,NE,2015-07-01,2026-05-06,2015-07-01 05:00:00+00:00,2026-05-07 04:00:00+00:00,95112,95112
7,NW,2015-07-01,2026-05-06,2015-07-01 07:00:00+00:00,2026-05-07 07:00:00+00:00,1967232,95113
8,NY,2015-07-01,2026-05-06,2015-07-01 05:00:00+00:00,2026-05-07 04:00:00+00:00,95112,95112
9,SE,2015-07-01,2026-05-06,2015-07-01 06:00:00+00:00,2026-05-07 05:00:00+00:00,244296,95112
10,SW,2015-07-01,2026-05-06,2015-07-01 08:00:00+00:00,2026-05-07 07:00:00+00:00,850680,95112
11,TEN,2015-07-01,2026-05-06,2015-07-01 06:00:00+00:00,2026-05-07 05:00:00+00:00,95112,95112
12,TEX,2015-07-01,2026-05-06,2015-07-01 06:00:00+00:00,2026-05-07 05:00:00+00:00,95112,95112

================================================================================
RECOMMENDED LOCAL-DATE CUTOFF
================================================================================
First local date complete for all regions: NaT
Last local date complete for all regions: NaT

If you split by Data Date, use an exclusive test_end_date one day after the last complete date:
No complete local date found for all regions.